import { useRef, useState } from "react";
import { Pressable, StyleSheet, Text, View } from "react-native";

import type { AuthenticatedSession } from "../../contracts/session";
import { useInvalidateEvent } from "../../core/query/useInvalidation";
import { canPerformOperation } from "../../core/session/operationCapabilities";
import { pickDocument, type SelectedAsset, TransferHttpError } from "../../platform/files";
import { useConfiguredRuntime } from "../../runtime/RuntimeProvider";
import { Button, Field, StateView } from "../../ui/primitives";
import { colors, fonts, radii, spacing } from "../../ui/tokens";
import { createIdempotencyKey, parseInrToPaise } from "../finance/money";
import { extractRecords, isRecord, recordId, recordSubtitle, recordTitle } from "../workspace/recordPresentation";

const RECEIPT_POLICY = { acceptedMimeTypes: ["application/pdf", "image/jpeg", "image/png", "image/webp"], maxBytes: 25 * 1024 * 1024 } as const;
function sourceKey(record: Record<string, unknown>): string | null { const source = record.estimateSource; return isRecord(source) && typeof source.sourceLineItemKey === "string" ? source.sourceLineItemKey : typeof record.sourceLineItemKey === "string" ? record.sourceLineItemKey : null; }

export function ProcurementProject({ projectId, data, session, onRefresh }: { readonly projectId: string; readonly data: unknown; readonly session: AuthenticatedSession; readonly onRefresh: () => void }) {
  const context = useConfiguredRuntime(); const invalidate = useInvalidateEvent(); const records = extractRecords(data); const canPost = canPerformOperation(session, "POST /procurement/projects/:projectId/expenses");
  const [selected, setSelected] = useState<Record<string, unknown> | null>(null); const [amount, setAmount] = useState(""); const [date, setDate] = useState(() => new Date().toISOString().slice(0, 10)); const [description, setDescription] = useState(""); const [vendor, setVendor] = useState(""); const [reference, setReference] = useState(""); const [receipt, setReceipt] = useState<SelectedAsset | null>(null); const [error, setError] = useState<string | null>(null); const [pending, setPending] = useState(false); const [progress, setProgress] = useState<number | null>(null); const key = useRef(createIdempotencyKey());
  const change = (setter: (value: string) => void) => (value: string) => { setter(value); key.current = createIdempotencyKey(); setError(null); };
  const choose = async () => { try { const result = await pickDocument(RECEIPT_POLICY); if (result.status === "selected") { setReceipt(result.asset); key.current = createIdempotencyKey(); setError(null); } } catch (cause) { setError(cause instanceof Error ? cause.message : "The receipt could not be selected."); } };
  const submit = async () => { const amountPaise = parseInrToPaise(amount); const sourceLineItemKey = selected ? sourceKey(selected) : null; if (!amountPaise || !description.trim() || !sourceLineItemKey || !receipt) { setError("Choose an approved item and receipt, then enter a positive amount and description."); return; } if (!/^\d{4}-\d{2}-\d{2}$/.test(date)) { setError("Enter the incurred date as YYYY-MM-DD."); return; } setPending(true); setProgress(0); try { await context.runtime.transfers.upload({ path: `/procurement/projects/${encodeURIComponent(projectId)}/expenses`, fileUri: receipt.uri, fileName: receipt.name, mimeType: receipt.mimeType, fieldName: "receipt", maxBytes: RECEIPT_POLICY.maxBytes, parameters: { sourceLineItemKey, amountPaise: String(amountPaise), incurredAt: `${date}T00:00:00.000Z`, description: description.trim(), vendor: vendor.trim(), reference: reference.trim(), idempotencyKey: key.current }, onProgress: (value) => setProgress(value.fraction) }).result; key.current = createIdempotencyKey(); setSelected(null); setAmount(""); setDescription(""); setVendor(""); setReference(""); setReceipt(null); setProgress(null); await invalidate("procurement-changed"); } catch (cause) { setError(cause instanceof TransferHttpError && cause.status === 409 ? "This cost may already be recorded or its approved source changed. Refresh before retrying." : cause instanceof Error ? cause.message : "The procurement cost could not be confirmed. Retry uses the same request identity."); } finally { setPending(false); } };
  return <View style={styles.section}><View style={styles.heading}><Text accessibilityRole="header" style={styles.title}>Approved procurement items</Text><Text style={styles.copy}>Every cost remains linked to its approved estimate source.</Text></View>{records.length === 0 ? <StateView title="No approved items" message="Approved estimate items will appear when this project is ready for procurement." /> : <View style={styles.list}>{records.map((record, index) => { const id = recordId(record) ?? `item-${index}`; const available = Boolean(sourceKey(record)); return <Pressable key={id} accessibilityRole={canPost && available ? "radio" : "text"} accessibilityState={{ selected: selected === record, disabled: !available }} disabled={!canPost || !available || pending} onPress={() => { setSelected(record); key.current = createIdempotencyKey(); setError(null); }} style={[styles.item, selected === record ? styles.selected : null]}><Text style={styles.itemTitle}>{recordTitle(record, index)}</Text>{recordSubtitle(record) ? <Text style={styles.copy}>{recordSubtitle(record)}</Text> : null}{!available ? <Text style={styles.warning}>Approved source unavailable</Text> : null}</Pressable>; })}</View>}
    {canPost && selected ? <View style={styles.form}><Text accessibilityRole="header" style={styles.formTitle}>Record cost for {recordTitle(selected, 0)}</Text><Field label="Amount (INR)" value={amount} onChangeText={change(setAmount)} keyboardType="decimal-pad" /><Field label="Incurred date (YYYY-MM-DD)" value={date} onChangeText={change(setDate)} /><Field label="Description" value={description} onChangeText={change(setDescription)} multiline /><Field label="Vendor (optional)" value={vendor} onChangeText={change(setVendor)} /><Field label="Reference (optional)" value={reference} onChangeText={change(setReference)} /><Button label={receipt ? `Receipt: ${receipt.name}` : "Choose receipt"} variant="secondary" disabled={pending} onPress={() => void choose()} />{progress !== null ? <Text accessibilityLiveRegion="polite" style={styles.copy}>{progress >= 1 ? "Upload complete. Recording cost…" : `Uploading ${Math.round(progress * 100)}%`}</Text> : null}{error ? <Text accessibilityLiveRegion="assertive" style={styles.error}>{error}</Text> : null}<View style={styles.actions}><View style={styles.action}><Button label="Cancel" variant="quiet" disabled={pending} onPress={() => { setSelected(null); setError(null); }} /></View><View style={styles.action}><Button label="Record cost" loading={pending} onPress={() => void submit()} /></View></View></View> : null}
    {!selected && error ? <Text accessibilityLiveRegion="assertive" style={styles.error}>{error}</Text> : null}<Button label="Refresh procurement" variant="secondary" onPress={onRefresh} /></View>;
}

const styles = StyleSheet.create({ section: { gap: spacing.lg }, heading: { gap: spacing.xs }, title: { color: colors.ink, fontFamily: fonts.semibold, fontSize: 22 }, copy: { color: colors.inkMuted, fontFamily: fonts.regular, fontSize: 12, lineHeight: 18 }, list: { gap: spacing.sm }, item: { minHeight: 68, padding: spacing.md, gap: 4, borderRadius: radii.surface, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.surface }, selected: { borderColor: colors.violet, borderWidth: 2 }, itemTitle: { color: colors.ink, fontFamily: fonts.semibold, fontSize: 14 }, warning: { color: colors.warning, fontFamily: fonts.medium, fontSize: 11 }, form: { gap: spacing.sm, padding: spacing.md, borderRadius: radii.surface, backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border }, formTitle: { color: colors.ink, fontFamily: fonts.semibold, fontSize: 17 }, error: { color: colors.danger, fontFamily: fonts.regular, fontSize: 12 }, actions: { flexDirection: "row", gap: spacing.sm }, action: { flex: 1 } });
