import type { PermissionCode } from "./authorization";

export type SuperAdminBehavior =
  | "self"
  | "global_read"
  | "admin_override"
  | "deny_personal";

interface ProtectedOperationPermission {
  readonly operation: `${"GET" | "POST" | "PUT" | "PATCH" | "DELETE"} /${string}`;
  readonly permission: PermissionCode;
}

export interface ProtectedOperation extends ProtectedOperationPermission {
  readonly superAdminBehavior: SuperAdminBehavior;
}

const PROTECTED_OPERATION_PERMISSIONS = [
  {"operation":"GET /auth/me","permission":"identity.self.read"},
  {"operation":"PUT /auth/me/profile-photo","permission":"identity.self.profile_photo.manage"},
  {"operation":"DELETE /auth/me/profile-photo","permission":"identity.self.profile_photo.manage"},
  {"operation":"GET /users/:userId/profile-photo","permission":"identity.self.read"},
  {"operation":"GET /projects","permission":"projects.list"},
  {"operation":"GET /client/project-summaries","permission":"projects.client_summary.read"},
  {"operation":"POST /projects","permission":"projects.create"},
  {"operation":"GET /projects/:projectId","permission":"projects.read"},
  {"operation":"GET /projects/:projectId/design-workflow","permission":"projects.design_workflow.read"},
  {"operation":"GET /projects/:projectId/design-workflow/furniture-uoms","permission":"projects.design_workflow.read"},
  {"operation":"POST /projects/:projectId/design-workflow/furniture-uoms","permission":"projects.design_workflow.act"},
  {"operation":"POST /projects/:projectId/design-workflow/actions","permission":"projects.design_workflow.act"},
  {"operation":"GET /projects/:projectId/design-workflow/history/:eventId/proof","permission":"projects.design_workflow.read"},
  {"operation":"GET /projects/:projectId/design-workflow/history/:eventId/media/:mediaId","permission":"projects.design_workflow.read"},
  {"operation":"GET /design-workflow/payment-confirmations","permission":"projects.design_workflow.payments.read"},
  {"operation":"POST /projects/:projectId/floors","permission":"projects.floor.create"},
  {"operation":"POST /floors/:floorId/stages","permission":"projects.stage.create"},
  {"operation":"POST /stages/:stageId/tasks","permission":"projects.task.create"},
  {"operation":"GET /tasks/:taskId/events","permission":"design.task_events.read"},
  {"operation":"PATCH /tasks/:taskId","permission":"design.task.self.update"},
  {"operation":"PATCH /tasks/:taskId/deadline","permission":"design.task_deadline.update"},
  {"operation":"GET /organization/managers","permission":"organization.managers.read"},
  {"operation":"GET /organization/team","permission":"organization.team.read"},
  {"operation":"GET /organization/tree","permission":"organization.tree.read"},
  {"operation":"GET /organization/managers/:managerId/designers","permission":"organization.manager_designers.read"},
  {"operation":"GET /designers/:designerId/summary","permission":"organization.designer_summary.read"},
  {"operation":"GET /kpis/users/:userId/tasks","permission":"organization.user_tasks.read"},
  {"operation":"GET /kpis/users/:userId","permission":"organization.user_kpi.read"},
  {"operation":"POST /evaluations","permission":"organization.evaluation.create"},
  {"operation":"GET /evaluations/:subjectId","permission":"organization.evaluation.read"},
  {"operation":"GET /projects/:projectId/activity","permission":"audit.project_activity.read"},
  {"operation":"GET /designers/:designerId/audit","permission":"audit.designer.read"},
  {"operation":"GET /audit","permission":"audit.read"},
  {"operation":"GET /client/latest-approved-versions","permission":"design.client_latest_approved.read"},
  {"operation":"POST /tasks/:taskId/design-versions","permission":"design.version.upload"},
  {"operation":"GET /projects/:projectId/design-versions","permission":"design.version.read"},
  {"operation":"GET /design-versions/:versionId/extraction","permission":"design.version_extraction.read"},
  {"operation":"PATCH /design-versions/:versionId/approval","permission":"design.version.approve"},
  {"operation":"GET /design-versions/:versionId/download","permission":"design.version.download"},
  {"operation":"GET /design-versions/:versionId/sections","permission":"design.section_draft.read"},
  {"operation":"POST /design-versions/:versionId/sections","permission":"design.section.create"},
  {"operation":"PATCH /design-sections/:sectionId","permission":"design.section.update"},
  {"operation":"DELETE /design-sections/:sectionId","permission":"design.section.delete"},
  {"operation":"POST /design-versions/:versionId/retry-extraction","permission":"design.section_extraction.retry"},
  {"operation":"POST /design-versions/:versionId/submit-sections","permission":"design.section.submit"},
  {"operation":"GET /client/projects/:projectId/design-sections","permission":"design.client_sections.read"},
  {"operation":"POST /design-section-revisions/:revisionId/decision","permission":"design.client_section_decision"},
  {"operation":"GET /design-source-pages/:pageId/image","permission":"design.source_page_image.read"},
  {"operation":"GET /design-section-revisions/:revisionId/image","permission":"design.section_revision_image.read"},
  {"operation":"POST /estimates/:estimateId/design-uploads","permission":"estimation.design_upload.create"},
  {"operation":"GET /estimates/:estimateId/design-uploads","permission":"estimation.design_upload.read"},
  {"operation":"POST /estimate-design-uploads/:uploadId/retry","permission":"estimation.design_upload.retry"},
  {"operation":"GET /estimate-design-source-pages/:pageId/image","permission":"estimation.source_page_image.read"},
  {"operation":"POST /estimate-design-source-pages/:pageId/drawings","permission":"estimation.drawing.create"},
  {"operation":"GET /estimate-design-revisions/:revisionId/image","permission":"estimation.design_revision_image.read"},
  {"operation":"GET /client/estimates/:estimateId/design-drawings","permission":"estimation.client_drawings.read"},
  {"operation":"PUT /client/estimate-design-revisions/:revisionId/annotation-draft","permission":"estimation.client_annotation_draft.save"},
  {"operation":"POST /client/estimate-design-revisions/:revisionId/decision","permission":"estimation.client_drawing_decision"},
  {"operation":"PATCH /estimate-design-drawings/:drawingId","permission":"estimation.drawing.update"},
  {"operation":"PUT /estimate-design-drawings/:drawingId/estimate-item","permission":"estimation.drawing.estimate_item.assign"},
  {"operation":"DELETE /estimate-design-drawings/:drawingId","permission":"estimation.drawing.delete"},
  {"operation":"POST /estimate-design-drawings/:drawingId/replacement","permission":"estimation.drawing.replace"},
  {"operation":"POST /estimates/:estimateId/design-drawings/submit","permission":"estimation.drawing.submit"},
  {"operation":"GET /client/estimates/:estimateId/plan-review","permission":"estimation.client_plan_review.read"},
  {"operation":"GET /client/estimate-plan-pages/:pageId/thumbnail","permission":"estimation.client_plan_review.read"},
  {"operation":"GET /client/estimate-plan-pages/:pageId/current-image","permission":"estimation.client_plan_review.read"},
  {"operation":"PUT /client/estimate-plan-pages/:pageId/annotation-draft","permission":"estimation.client_plan_annotation_draft.save"},
  {"operation":"POST /client/estimate-plan-pages/:pageId/target-preview","permission":"estimation.client_plan_target_preview"},
  {"operation":"POST /client/estimate-plan-pages/:pageId/change-requests","permission":"estimation.client_plan_change_request.create"},
  {"operation":"PUT /client/estimate-plan-change-requests/:requestId","permission":"estimation.client_plan_change_request.update"},
  {"operation":"GET /estimate-plan-change-requests","permission":"estimation.plan_change_request.read"},
  {"operation":"GET /estimate-plan-change-requests/:requestId","permission":"estimation.plan_change_request.read"},
  {"operation":"PUT /estimate-plan-change-requests/:requestId/targets","permission":"estimation.plan_change_request.targets.update"},
  {"operation":"POST /estimate-plan-change-requests/:requestId/resolve-page","permission":"estimation.plan_change_request.resolve_page"},
  {"operation":"GET /estimate-plan-pages/:pageId/current-image","permission":"estimation.plan_page_image.read"},
  {"operation":"GET /leads","permission":"estimation.lead.list"},
  {"operation":"POST /leads","permission":"estimation.lead.create"},
  {"operation":"GET /leads/:leadId","permission":"estimation.lead.read"},
  {"operation":"PATCH /leads/:leadId","permission":"estimation.lead.update"},
  {"operation":"GET /leads/:leadId/activities","permission":"estimation.lead_activity.read"},
  {"operation":"POST /leads/:leadId/activities","permission":"estimation.lead_activity.create"},
  {"operation":"GET /leads/:leadId/estimate","permission":"estimation.estimate.read"},
  {"operation":"GET /estimates","permission":"estimation.estimate.list"},
  {"operation":"PUT /leads/:leadId/estimate","permission":"estimation.estimate.save"},
  {"operation":"POST /leads/:leadId/estimate/submit","permission":"estimation.estimate.submit"},
  {"operation":"GET /estimates/:estimateId/pdf","permission":"estimation.estimate_pdf.download"},
  {"operation":"GET /estimates/review-queue","permission":"estimation.review_queue.read"},
  {"operation":"GET /estimates/designers","permission":"estimation.assignable_designers.read"},
  {"operation":"POST /estimates/:estimateId/assign","permission":"estimation.designer_assignment.create"},
  {"operation":"POST /estimates/:estimateId/designer-decision","permission":"estimation.designer_assignment.decision"},
  {"operation":"POST /estimates/:estimateId/send-client","permission":"estimation.estimate.send_client"},
  {"operation":"GET /client/estimates","permission":"estimation.client_estimate.list"},
  {"operation":"GET /client/estimates/:estimateId/pdf","permission":"estimation.client_estimate_pdf.download"},
  {"operation":"POST /client/estimates/:estimateId/decision","permission":"estimation.client_estimate.decision"},
  {"operation":"GET /auth/authorization","permission":"identity.authorization.read"},
  {"operation":"GET /admin/users","permission":"identity.users.read"},
  {"operation":"PATCH /admin/users/:userId","permission":"identity.users.update"},
  {"operation":"POST /access-requests","permission":"access_request.create"},
  {"operation":"GET /access-requests/mine","permission":"access_request.self.read"},
  {"operation":"POST /access-requests/:requestId/cancel","permission":"access_request.self.cancel"},
  {"operation":"GET /access-requests/review","permission":"access_request.review.read"},
  {"operation":"POST /access-requests/:requestId/decision","permission":"access_request.review.decide"},
  {"operation":"POST /project-access-grants/:grantId/revoke","permission":"project_access_grant.revoke"},
  {"operation":"GET /admin/projects","permission":"projects.list"},
  {"operation":"GET /admin/projects/:projectId","permission":"projects.read"},
  {"operation":"POST /admin/projects","permission":"projects.initiate"},
  {"operation":"GET /admin/sales-managers","permission":"projects.initiate"},
  {"operation":"GET /admin/estimators","permission":"organization.estimators.read"},
  {"operation":"GET /admin/user-invitations","permission":"identity.user_invitations.read"},
  {"operation":"POST /admin/user-invitations","permission":"identity.user_invitations.create"},
  {"operation":"POST /admin/user-invitations/:invitationId/resend","permission":"identity.user_invitations.resend"},
  {"operation":"POST /admin/user-invitations/:invitationId/revoke","permission":"identity.user_invitations.revoke"},
  {"operation":"GET /admin/estimate-client-response-tasks","permission":"estimation.client_response_tasks.read"},
  {"operation":"GET /admin/estimate-client-response-tasks/:roundId","permission":"estimation.client_response_tasks.read"},
  {"operation":"GET /admin/estimate-client-response-tasks/:roundId/pdf","permission":"estimation.client_response_tasks.read"},
  {"operation":"GET /admin/estimate-client-response-tasks/:roundId/proof","permission":"estimation.client_response_proof.read"},
  {"operation":"POST /admin/estimate-client-response-tasks/:roundId/decision","permission":"estimation.client_response_tasks.decide"},
  {"operation":"POST /estimates/:estimateId/client-email/retry","permission":"estimation.estimate_email.retry"},
  {"operation":"GET /admin/designers","permission":"design.plan_assignment.manage"},
  {"operation":"POST /admin/projects/:projectId/design-assignment","permission":"design.plan_assignment.manage"},
  {"operation":"GET /designer/design-plan-tasks","permission":"design.plan_task.read"},
  {"operation":"GET /admin/design-plan-response-tasks","permission":"design.plan_response_tasks.read"},
  {"operation":"GET /admin/design-plan-response-tasks/:roundId/attachments/:attachmentIndex","permission":"design.plan_response_tasks.read"},
  {"operation":"GET /admin/design-plan-response-tasks/:roundId/proof","permission":"design.plan_response_tasks.read"},
  {"operation":"POST /admin/design-plan-response-tasks/:roundId/email/retry","permission":"design.plan_response_tasks.decide"},
  {"operation":"POST /admin/design-plan-response-tasks/:roundId/decision","permission":"design.plan_response_tasks.decide"},
  {"operation":"GET /admin/workers","permission":"execution.worker_assignment.override"},
  {"operation":"GET /admin/projects/:projectId/workflow-tasks","permission":"execution.worker_assignment.override"},
  {"operation":"GET /admin/projects/:projectId/section-assignments","permission":"execution.worker_assignment.override"},
  {"operation":"POST /execution/worker-assignments/override","permission":"execution.worker_assignment.override"},
  {"operation":"POST /execution/section-worker-assignments/override","permission":"execution.worker_assignment.override"},
  {"operation":"GET /workflow-tasks","permission":"workflow.tasks.read"},
  {"operation":"PATCH /workflow-tasks/:taskId","permission":"workflow.tasks.update"},
  {"operation":"GET /procurement/projects/:projectId/items","permission":"procurement.items.read"},
  {"operation":"GET /procurement/uoms","permission":"procurement.items.read"},
  {"operation":"GET /procurement/projects/:projectId/items/:itemId","permission":"procurement.items.read"},
  {"operation":"POST /procurement/projects/:projectId/items","permission":"procurement.items.manage"},
  {"operation":"PATCH /procurement/projects/:projectId/items/:itemId","permission":"procurement.items.manage"},
  {"operation":"GET /procurement/suggestion-projects","permission":"procurement.vendor_suggestions.read"},
  {"operation":"GET /procurement/projects/:projectId/vendor-suggestions","permission":"procurement.vendor_suggestions.read"},
  {"operation":"POST /procurement/projects/:projectId/vendor-suggestions","permission":"procurement.vendor_suggestions.manage"},
  {"operation":"PATCH /procurement/projects/:projectId/vendor-suggestions/:suggestionId","permission":"procurement.vendor_suggestions.manage"},
  {"operation":"GET /procurement/vendors","permission":"procurement.vendors.read"},
  {"operation":"POST /procurement/vendors","permission":"procurement.vendors.create"},
  {"operation":"GET /procurement/projects","permission":"procurement.workspace.read"},
  {"operation":"POST /procurement/projects/:projectId/expenses","permission":"procurement.expense.create"},
  {"operation":"GET /procurement/projects/:projectId/entries/:entryId/document","permission":"procurement.document.read"},
  {"operation":"GET /finance/projects","permission":"finance.bucket.read"},
  {"operation":"GET /finance/projects/:projectId","permission":"finance.bucket.read"},
  {"operation":"GET /finance/projects/:projectId/entries","permission":"finance.entry.read"},
  {"operation":"GET /finance/projects/:projectId/entries/:entryId/document","permission":"finance.entry.read"},
  {"operation":"POST /finance/projects/:projectId/entries","permission":"finance.entry.create"},
  {"operation":"GET /admin/ai-estimator-knowledge/vendors/msme-certificate-upload-policy","permission":"ai_estimator_knowledge.configuration.read"},
  {"operation":"POST /admin/ai-estimator-knowledge/vendors/msme-certificate-uploads","permission":"ai_estimator_knowledge.configuration.create"},
  {"operation":"POST /admin/ai-estimator-knowledge/vendors/:id/msme-certificate-uploads","permission":"ai_estimator_knowledge.configuration.update"},
  {"operation":"GET /admin/ai-estimator-knowledge/vendors/:id/msme-certificate","permission":"ai_estimator_knowledge.configuration.read"},
  {"operation":"GET /admin/ai-estimator-knowledge/vendors/:id","permission":"ai_estimator_knowledge.configuration.read"},
  {"operation":"GET /admin/ai-estimator-knowledge/vendors/:id/photo","permission":"ai_estimator_knowledge.configuration.read"},
  {"operation":"PUT /admin/ai-estimator-knowledge/vendors/:id/photo","permission":"ai_estimator_knowledge.configuration.update"},
  {"operation":"DELETE /admin/ai-estimator-knowledge/vendors/:id/photo","permission":"ai_estimator_knowledge.configuration.update"},
  {"operation":"GET /admin/ai-estimator-knowledge/vendors/:id/allocation-baseline","permission":"ai_estimator_knowledge.configuration.read"},
  {"operation":"POST /admin/ai-estimator-knowledge/vendors/:id/allocation-baseline/:itemId","permission":"ai_estimator_knowledge.configuration.update"},
  {"operation":"GET /admin/ai-estimator-knowledge/baskets","permission":"ai_estimator_knowledge.configuration.read"},
  {"operation":"GET /admin/ai-estimator-knowledge/baskets/:basketId/quality","permission":"ai_estimator_knowledge.configuration.read"},
  {"operation":"GET /admin/ai-estimator-knowledge/quality-control-options","permission":"ai_estimator_knowledge.configuration.read"},
  {"operation":"POST /admin/ai-estimator-knowledge/quality-control-options","permission":"ai_estimator_knowledge.quality_control_options.create"},
  {"operation":"POST /admin/ai-estimator-knowledge/baskets","permission":"ai_estimator_knowledge.configuration.create"},
  {"operation":"PATCH /admin/ai-estimator-knowledge/baskets/:basketId","permission":"ai_estimator_knowledge.configuration.update"},
  {"operation":"PUT /admin/ai-estimator-knowledge/baskets/:basketId/quality","permission":"ai_estimator_knowledge.configuration.update"},
  {"operation":"DELETE /admin/ai-estimator-knowledge/baskets/:basketId","permission":"ai_estimator_knowledge.configuration.lifecycle"},
  {"operation":"GET /admin/ai-estimator-knowledge/baskets/:basketId/deletion-impact","permission":"ai_estimator_knowledge.configuration.lifecycle"},
  {"operation":"GET /admin/ai-estimator-knowledge/baskets/:basketId/sub-baskets","permission":"ai_estimator_knowledge.configuration.read"},
  {"operation":"GET /admin/ai-estimator-knowledge/baskets/:basketId/main-lines","permission":"ai_estimator_knowledge.configuration.read"},
  {"operation":"POST /admin/ai-estimator-knowledge/baskets/:basketId/sub-baskets","permission":"ai_estimator_knowledge.configuration.create"},
  {"operation":"PATCH /admin/ai-estimator-knowledge/baskets/:basketId/sub-baskets/:subBasketId","permission":"ai_estimator_knowledge.configuration.update"},
  {"operation":"GET /admin/ai-estimator-knowledge/baskets/:basketId/sub-baskets/:subBasketId/deletion-impact","permission":"ai_estimator_knowledge.configuration.lifecycle"},
  {"operation":"DELETE /admin/ai-estimator-knowledge/baskets/:basketId/sub-baskets/:subBasketId","permission":"ai_estimator_knowledge.configuration.lifecycle"},
  {"operation":"POST /admin/ai-estimator-knowledge/baskets/:basketId/main-lines","permission":"ai_estimator_knowledge.configuration.create"},
  {"operation":"PATCH /admin/ai-estimator-knowledge/main-lines/:mainLineId","permission":"ai_estimator_knowledge.configuration.update"},
  {"operation":"DELETE /admin/ai-estimator-knowledge/main-lines/:mainLineId","permission":"ai_estimator_knowledge.configuration.lifecycle"},
  {"operation":"GET /admin/ai-estimator-knowledge/items","permission":"ai_estimator_knowledge.configuration.read"},
  {"operation":"GET /admin/ai-estimator-knowledge/main-lines/:mainLineId","permission":"ai_estimator_knowledge.configuration.read"},
  {"operation":"GET /admin/ai-estimator-knowledge/main-lines/:mainLineId/history","permission":"ai_estimator_knowledge.configuration.read"},
  {"operation":"POST /admin/ai-estimator-knowledge/main-lines/:mainLineId/revisions","permission":"ai_estimator_knowledge.configuration.create"},
  {"operation":"GET /admin/ai-estimator-knowledge/main-lines/:mainLineId/revisions/:revisionId/sections/:sectionKey","permission":"ai_estimator_knowledge.configuration.read"},
  {"operation":"PUT /admin/ai-estimator-knowledge/main-lines/:mainLineId/revisions/:revisionId/sections/:sectionKey","permission":"ai_estimator_knowledge.configuration.update"},
  {"operation":"POST /admin/ai-estimator-knowledge/main-lines/:mainLineId/revisions/:revisionId/activate","permission":"ai_estimator_knowledge.configuration.lifecycle"},
  {"operation":"POST /admin/ai-estimator-knowledge/main-lines/:mainLineId/deactivate","permission":"ai_estimator_knowledge.configuration.lifecycle"},
  {"operation":"POST /admin/ai-estimator-knowledge/main-lines/:mainLineId/duplicate","permission":"ai_estimator_knowledge.configuration.create"},
  {"operation":"POST /admin/ai-estimator-knowledge/preview","permission":"ai_estimator_knowledge.configuration.read"},
  {"operation":"GET /admin/ai-estimator-knowledge/uoms","permission":"ai_estimator_knowledge.configuration.read"},
  {"operation":"POST /admin/ai-estimator-knowledge/uoms","permission":"ai_estimator_knowledge.configuration.create"},
  {"operation":"PATCH /admin/ai-estimator-knowledge/uoms/:id","permission":"ai_estimator_knowledge.configuration.update"},
  {"operation":"DELETE /admin/ai-estimator-knowledge/uoms/:id","permission":"ai_estimator_knowledge.configuration.lifecycle"},
  {"operation":"GET /admin/ai-estimator-knowledge/vendors","permission":"ai_estimator_knowledge.configuration.read"},
  {"operation":"POST /admin/ai-estimator-knowledge/vendors","permission":"ai_estimator_knowledge.configuration.create"},
  {"operation":"PATCH /admin/ai-estimator-knowledge/vendors/:id","permission":"ai_estimator_knowledge.configuration.update"},
  {"operation":"DELETE /admin/ai-estimator-knowledge/vendors/:id","permission":"ai_estimator_knowledge.configuration.lifecycle"},
  {"operation":"GET /admin/ai-estimator-knowledge/taxes","permission":"ai_estimator_knowledge.configuration.read"},
  {"operation":"POST /admin/ai-estimator-knowledge/taxes","permission":"ai_estimator_knowledge.configuration.create"},
  {"operation":"PATCH /admin/ai-estimator-knowledge/taxes/:id","permission":"ai_estimator_knowledge.configuration.update"},
  {"operation":"DELETE /admin/ai-estimator-knowledge/taxes/:id","permission":"ai_estimator_knowledge.configuration.lifecycle"},
  {"operation":"GET /admin/ai-estimator-knowledge/priorities","permission":"ai_estimator_knowledge.configuration.read"},
  {"operation":"POST /admin/ai-estimator-knowledge/priorities","permission":"ai_estimator_knowledge.configuration.create"},
  {"operation":"PATCH /admin/ai-estimator-knowledge/priorities/:id","permission":"ai_estimator_knowledge.configuration.update"},
  {"operation":"DELETE /admin/ai-estimator-knowledge/priorities/:id","permission":"ai_estimator_knowledge.configuration.lifecycle"},
  {"operation":"GET /admin/ai-estimator-knowledge/surfaces","permission":"ai_estimator_knowledge.configuration.read"},
  {"operation":"POST /admin/ai-estimator-knowledge/surfaces","permission":"ai_estimator_knowledge.configuration.create"},
  {"operation":"PATCH /admin/ai-estimator-knowledge/surfaces/:id","permission":"ai_estimator_knowledge.configuration.update"},
  {"operation":"DELETE /admin/ai-estimator-knowledge/surfaces/:id","permission":"ai_estimator_knowledge.configuration.lifecycle"},
  {"operation":"GET /admin/ai-estimator-knowledge/modes","permission":"ai_estimator_knowledge.configuration.read"},
  {"operation":"POST /admin/ai-estimator-knowledge/modes","permission":"ai_estimator_knowledge.configuration.create"},
  {"operation":"PATCH /admin/ai-estimator-knowledge/modes/:id","permission":"ai_estimator_knowledge.configuration.update"},
  {"operation":"DELETE /admin/ai-estimator-knowledge/modes/:id","permission":"ai_estimator_knowledge.configuration.lifecycle"},
  {"operation":"POST /ai-estimator-knowledge/context","permission":"ai_estimator_knowledge.context.read"},
  {"operation":"GET /admin/dashboard/overview","permission":"admin.dashboard.read"},
  {"operation":"GET /admin/dashboard/projects","permission":"admin.dashboard.read"},
  {"operation":"GET /admin/dashboard/workforce","permission":"admin.dashboard.read"},
  {"operation":"DELETE /estimate-design-uploads/:uploadId","permission":"estimation.design_upload.delete"},
  {"operation":"POST /estimate-plan-change-requests/:requestId/replacement-upload","permission":"estimation.drawing.replace"},
  {"operation":"GET /notifications","permission":"chat.read"},
  {"operation":"PUT /notifications/:notificationId/read","permission":"chat.read_state"},
  {"operation":"GET /notifications/events","permission":"chat.read"},
  {"operation":"GET /project-messages","permission":"chat.read"},
  {"operation":"GET /projects/:projectId/chat/attachment-policy","permission":"chat.read"},
  {"operation":"POST /projects/:projectId/chat/attachments","permission":"chat.send"},
  {"operation":"DELETE /projects/:projectId/chat/attachments/:attachmentId","permission":"chat.send"},
  {"operation":"GET /projects/:projectId/chat/attachments/:attachmentId/content","permission":"chat.read"},
  {"operation":"GET /projects/:projectId/chat/attachments/:attachmentId/preview","permission":"chat.read"},
  {"operation":"GET /projects/:projectId/chat","permission":"chat.read"},
  {"operation":"GET /projects/:projectId/chat/participants","permission":"chat.read"},
  {"operation":"GET /projects/:projectId/chat/action-types","permission":"chat.read"},
  {"operation":"POST /projects/:projectId/chat/action-types","permission":"chat.action_types.manage"},
  {"operation":"PATCH /projects/:projectId/chat/project-name","permission":"chat.project_name.manage"},
  {"operation":"POST /projects/:projectId/chat/participants/:userId/remove","permission":"chat.participants.manage"},
  {"operation":"POST /projects/:projectId/chat/participants/:userId/restore","permission":"chat.participants.manage"},
  {"operation":"GET /projects/:projectId/chat/participant-options","permission":"chat.participants.manage"},
  {"operation":"POST /projects/:projectId/chat/participants","permission":"chat.participants.manage"},
  {"operation":"POST /projects/:projectId/chat/participants/:selectionId/revoke","permission":"chat.participants.manage"},
  {"operation":"GET /projects/:projectId/chat/messages","permission":"chat.read"},
  {"operation":"POST /projects/:projectId/chat/messages","permission":"chat.send"},
  {"operation":"PATCH /projects/:projectId/chat/messages/:messageId/issue","permission":"chat.issue"},
  {"operation":"PUT /projects/:projectId/chat/read","permission":"chat.read_state"},
  {"operation":"PUT /projects/:projectId/chat/typing","permission":"chat.send"},
  {"operation":"GET /projects/:projectId/chat/events","permission":"chat.read"},
] as const satisfies readonly ProtectedOperationPermission[];

// This ordered mirror is intentionally separate from permission data so the
// generated operation list stays compact while retaining the backend's
// Super Admin exception for every protected route. The drift test compares the
// composed objects to the canonical registry, including this field.
const SUPER_ADMIN_BEHAVIORS = [
  "self", "self", "self", "global_read", "global_read", "global_read", "deny_personal", "global_read",
  "global_read", "global_read", "admin_override", "admin_override", "global_read", "global_read", "global_read", "deny_personal",
  "deny_personal", "deny_personal", "global_read", "deny_personal", "admin_override", "global_read", "global_read", "global_read",
  "global_read", "global_read", "global_read", "global_read", "admin_override", "global_read", "global_read", "global_read",
  "global_read", "global_read", "deny_personal", "global_read", "global_read", "admin_override", "global_read", "global_read",
  "deny_personal", "deny_personal", "deny_personal", "deny_personal", "deny_personal", "global_read", "deny_personal", "global_read",
  "global_read", "deny_personal", "global_read", "deny_personal", "global_read", "deny_personal", "global_read", "global_read",
  "deny_personal", "deny_personal", "deny_personal", "deny_personal", "deny_personal", "deny_personal", "deny_personal", "global_read",
  "global_read", "global_read", "deny_personal", "global_read", "deny_personal", "deny_personal", "global_read", "global_read",
  "admin_override", "admin_override", "global_read", "global_read", "deny_personal", "global_read", "deny_personal", "global_read",
  "deny_personal", "global_read", "global_read", "deny_personal", "deny_personal", "global_read", "global_read", "global_read",
  "admin_override", "deny_personal", "deny_personal", "global_read", "global_read", "deny_personal", "self", "global_read",
  "admin_override", "deny_personal", "self", "deny_personal", "global_read", "admin_override", "admin_override", "global_read",
  "global_read", "admin_override", "global_read", "global_read", "global_read", "admin_override", "admin_override", "admin_override",
  "global_read", "global_read", "global_read", "global_read", "admin_override", "admin_override", "global_read", "admin_override",
  "deny_personal", "global_read", "global_read", "global_read", "admin_override", "admin_override", "global_read", "global_read",
  "global_read", "admin_override", "admin_override", "deny_personal", "deny_personal", "deny_personal", "deny_personal", "deny_personal",
  "deny_personal", "deny_personal", "global_read", "global_read", "deny_personal", "deny_personal", "global_read", "deny_personal",
  "deny_personal", "deny_personal", "deny_personal", "global_read", "global_read", "global_read", "global_read", "admin_override",
  "global_read", "admin_override", "admin_override", "global_read", "global_read", "global_read", "admin_override", "admin_override",
  "global_read", "admin_override", "global_read", "global_read", "global_read", "admin_override", "admin_override", "admin_override",
  "admin_override", "admin_override", "admin_override", "global_read", "global_read", "admin_override", "admin_override", "admin_override",
  "admin_override", "admin_override", "admin_override", "admin_override", "global_read", "global_read", "global_read", "admin_override",
  "global_read", "admin_override", "admin_override", "admin_override", "admin_override", "global_read", "global_read", "admin_override",
  "admin_override", "admin_override", "global_read", "admin_override", "admin_override", "admin_override", "global_read", "admin_override",
  "admin_override", "admin_override", "global_read", "admin_override", "admin_override", "admin_override", "global_read", "admin_override",
  "admin_override", "admin_override", "global_read", "admin_override", "admin_override", "admin_override", "global_read", "global_read",
  "global_read", "global_read", "deny_personal", "deny_personal", "self", "self", "self", "global_read",
  "global_read", "self", "self", "global_read", "global_read", "global_read", "global_read", "global_read",
  "admin_override", "admin_override", "admin_override", "admin_override", "global_read", "admin_override", "admin_override", "global_read",
  "self", "admin_override", "self", "self", "global_read",
] as const satisfies readonly SuperAdminBehavior[];

function behaviorAt(index: number): SuperAdminBehavior {
  const behavior = SUPER_ADMIN_BEHAVIORS[index];
  if (!behavior) throw new Error("Protected operation behavior mirror is incomplete.");
  return behavior;
}

export const PROTECTED_OPERATIONS: readonly ProtectedOperation[] = Object.freeze(
  PROTECTED_OPERATION_PERMISSIONS.map((entry, index) =>
    Object.freeze({ ...entry, superAdminBehavior: behaviorAt(index) })
  )
);

export const PUBLIC_API_OPERATIONS = [
  "GET /health",
  "POST /auth/login",
  "POST /auth/client-signup",
  "POST /auth/password-reset/request",
  "POST /auth/password-reset/inspect",
  "POST /auth/password-reset/complete",
  "POST /auth/user-invitations/inspect",
  "POST /auth/user-invitations/accept"
] as const;
