import { useMutation, useQuery } from "@tanstack/react-query";
import { useState } from "react";
import { Pressable, StyleSheet, Text, View } from "react-native";

import type { AuthenticatedSession } from "../../contracts/session";
import { ApiError } from "../../core/http/apiClient";
import { privateQueryKey } from "../../core/query/queryClient";
import { useInvalidateEvent } from "../../core/query/useInvalidation";
import { canPerformOperation } from "../../core/session/operationCapabilities";
import { useConfiguredRuntime } from "../../runtime/RuntimeProvider";
import { Button, Field } from "../../ui/primitives";
import { colors, fonts, radii, spacing } from "../../ui/tokens";
import { splitStableIds, validBudgetRange, validSchedule } from "./projectCreateModel";

interface Option { readonly id: string; readonly name: string; readonly email?: string }
interface Page<T> { readonly items: readonly T[] }
function failure(cause: unknown): string { return cause instanceof ApiError ? cause.message : "The project could not be created."; }

function OptionPicker({ path, label, selected, onSelect }: { readonly path: string; readonly label: string; readonly selected: Option | null; readonly onSelect: (value: Option) => void }) {
  const context = useConfiguredRuntime(); const session = context.session.status === "authenticated" ? context.session.session : null; const [search, setSearch] = useState("");
  const query = useQuery({ queryKey: privateQueryKey({ environmentId: context.environment.environment.id, userId: session?.user.id ?? "" }, "management", "project-option", path, search), queryFn: ({ signal }) => context.runtime.api.authenticated.get<Page<Option>>(`${path}?search=${encodeURIComponent(search.trim())}&limit=20&offset=0`, { signal }), enabled: Boolean(session) });
  return <View style={styles.compact}><Field label={`Search ${label}`} value={search} onChangeText={setSearch} autoCapitalize="none" />{selected ? <Text accessibilityLiveRegion="polite" style={styles.selectedCopy}>Selected: {selected.name}</Text> : null}{query.isPending ? <Text style={styles.copy}>Loading options…</Text> : query.isError ? <Text style={styles.error}>Options could not be loaded.</Text> : <View accessibilityRole="radiogroup" style={styles.options}>{(query.data?.items ?? []).map((option) => <Pressable key={option.id} accessibilityRole="radio" accessibilityState={{ selected: selected?.id === option.id }} onPress={() => onSelect(option)} style={[styles.option, selected?.id === option.id ? styles.optionSelected : null]}><Text style={[styles.optionTitle, selected?.id === option.id ? styles.optionTitleSelected : null]}>{option.name}</Text>{option.email ? <Text style={[styles.optionCopy, selected?.id === option.id ? styles.optionTitleSelected : null]}>{option.email}</Text> : null}</Pressable>)}</View>}</View>;
}

export function DesignerProjectCreate({ session }: { readonly session: AuthenticatedSession }) {
  const context = useConfiguredRuntime(); const invalidate = useInvalidateEvent(); const [open, setOpen] = useState(false); const [manager, setManager] = useState<Option | null>(null); const [name, setName] = useState(""); const [location, setLocation] = useState(""); const [clientName, setClientName] = useState(""); const [clientEmail, setClientEmail] = useState(""); const [clientMobile, setClientMobile] = useState(""); const [clientAddress, setClientAddress] = useState(""); const [designerIds, setDesignerIds] = useState(""); const [start, setStart] = useState(""); const [end, setEnd] = useState(""); const [error, setError] = useState<string | null>(null);
  const mutation = useMutation({ mutationFn: async () => { if (!name.trim() || !location.trim() || !clientName.trim() || !clientEmail.trim() || !clientMobile.trim() || !clientAddress.trim() || !manager || !validSchedule(start, end)) throw new Error("Complete every required project, Client, manager and schedule field. The end must follow the start."); return context.runtime.api.authenticated.post("/projects", { name: name.trim(), clientName: clientName.trim(), clientEmail: clientEmail.trim(), clientMobile: clientMobile.trim(), clientAddress: clientAddress.trim(), assignedDesignerIds: splitStableIds(designerIds, session.user.id), managerId: manager.id, location: location.trim(), plannedStartAt: new Date(start).toISOString(), plannedEndAt: new Date(end).toISOString() }); }, onSuccess: async () => { setOpen(false); await invalidate("project-initiated"); }, onError: (cause) => setError(cause instanceof Error ? cause.message : failure(cause)) });
  if (!canPerformOperation(session, "POST /projects")) return null;
  if (!open) return <Button label="Create project" onPress={() => setOpen(true)} />;
  return <View style={styles.panel}><View><Text accessibilityRole="header" style={styles.title}>Create project</Text><Text style={styles.copy}>The project includes Lisno’s design workflow and remains scoped to the assigned team.</Text></View><Field label="Project name" value={name} onChangeText={setName} /><Field label="Location" value={location} onChangeText={setLocation} /><Field label="Client name" value={clientName} onChangeText={setClientName} /><Field label="Client email" value={clientEmail} onChangeText={setClientEmail} autoCapitalize="none" keyboardType="email-address" /><Field label="Client mobile" value={clientMobile} onChangeText={setClientMobile} keyboardType="phone-pad" /><Field label="Client address" value={clientAddress} onChangeText={setClientAddress} multiline /><OptionPicker path="/organization/managers" label="Design Manager" selected={manager} onSelect={setManager} /><Field label="Additional Designer IDs (optional)" value={designerIds} onChangeText={setDesignerIds} autoCapitalize="none" /><Field label="Planned start (ISO 8601)" value={start} onChangeText={setStart} /><Field label="Planned end (ISO 8601)" value={end} onChangeText={setEnd} />{error ? <Text accessibilityLiveRegion="assertive" style={styles.error}>{error}</Text> : null}<View style={styles.actions}><View style={styles.action}><Button label="Cancel" variant="quiet" disabled={mutation.isPending} onPress={() => setOpen(false)} /></View><View style={styles.action}><Button label="Create project" loading={mutation.isPending} onPress={() => mutation.mutate()} /></View></View></View>;
}

export function AdminProjectInitiate({ session }: { readonly session: AuthenticatedSession }) {
  const context = useConfiguredRuntime(); const invalidate = useInvalidateEvent(); const [open, setOpen] = useState(false); const salesManagerMode = session.user.role === "super_admin"; const [assignee, setAssignee] = useState<Option | null>(null); const [clientName, setClientName] = useState(""); const [clientEmail, setClientEmail] = useState(""); const [clientMobile, setClientMobile] = useState(""); const [projectName, setProjectName] = useState(""); const [location, setLocation] = useState(""); const [propertyType, setPropertyType] = useState(""); const [budgetMin, setBudgetMin] = useState(""); const [budgetMax, setBudgetMax] = useState(""); const [nextAction, setNextAction] = useState(""); const [nextActionAt, setNextActionAt] = useState(""); const [error, setError] = useState<string | null>(null);
  const mutation = useMutation({ mutationFn: async () => { if (!clientName.trim() || !clientEmail.trim() || !clientMobile.trim() || !projectName.trim() || !location.trim() || !propertyType.trim() || !nextAction.trim() || !assignee || !validBudgetRange(budgetMin, budgetMax) || Number.isNaN(new Date(nextActionAt).getTime())) throw new Error("Complete every field, choose an active assignee, enter a valid budget range and next-action time."); return context.runtime.api.authenticated.post("/admin/projects", { clientName: clientName.trim(), clientEmail: clientEmail.trim(), clientMobile: clientMobile.trim(), projectName: projectName.trim(), location: location.trim(), propertyType: propertyType.trim(), budgetMin: Number(budgetMin), budgetMax: Number(budgetMax), nextAction: nextAction.trim(), nextActionAt: new Date(nextActionAt).toISOString(), ...(salesManagerMode ? { salesManagerId: assignee.id } : { estimatorId: assignee.id }) }); }, onSuccess: async () => { setOpen(false); await invalidate("project-initiated"); }, onError: (cause) => setError(cause instanceof Error ? cause.message : failure(cause)) });
  if (!canPerformOperation(session, "POST /admin/projects")) return null;
  if (!open) return <Button label="Initiate project" onPress={() => setOpen(true)} />;
  return <View style={styles.panel}><View><Text accessibilityRole="header" style={styles.title}>Initiate project</Text><Text style={styles.copy}>Create the project and assign its Sales handoff.</Text></View><Field label="Project / property name" value={projectName} onChangeText={setProjectName} /><Field label="Property type" value={propertyType} onChangeText={setPropertyType} /><Field label="Location" value={location} onChangeText={setLocation} /><Field label="Client name" value={clientName} onChangeText={setClientName} /><Field label="Client email" value={clientEmail} onChangeText={setClientEmail} autoCapitalize="none" keyboardType="email-address" /><Field label="Client mobile" value={clientMobile} onChangeText={setClientMobile} keyboardType="phone-pad" /><Field label="Minimum budget" value={budgetMin} onChangeText={setBudgetMin} keyboardType="decimal-pad" /><Field label="Maximum budget" value={budgetMax} onChangeText={setBudgetMax} keyboardType="decimal-pad" /><Field label="Next action" value={nextAction} onChangeText={setNextAction} /><Field label="Next action time (ISO 8601)" value={nextActionAt} onChangeText={setNextActionAt} /><OptionPicker path={salesManagerMode ? "/admin/sales-managers" : "/admin/estimators"} label={salesManagerMode ? "Sales Manager" : "Sales user"} selected={assignee} onSelect={setAssignee} />{error ? <Text accessibilityLiveRegion="assertive" style={styles.error}>{error}</Text> : null}<View style={styles.actions}><View style={styles.action}><Button label="Cancel" variant="quiet" disabled={mutation.isPending} onPress={() => setOpen(false)} /></View><View style={styles.action}><Button label="Initiate" loading={mutation.isPending} onPress={() => mutation.mutate()} /></View></View></View>;
}

export function ProjectCreateAction({ session }: { readonly session: AuthenticatedSession }) {
  if (session.user.role === "designer") {
    return canPerformOperation(session, "POST /projects")
      ? <DesignerProjectCreate session={session} />
      : null;
  }
  return canPerformOperation(session, "POST /admin/projects")
    ? <AdminProjectInitiate session={session} />
    : null;
}

const styles = StyleSheet.create({ panel: { gap: spacing.md, padding: spacing.lg, borderRadius: radii.surface, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.surface }, compact: { gap: spacing.sm }, title: { color: colors.ink, fontFamily: fonts.semibold, fontSize: 20 }, copy: { color: colors.inkMuted, fontFamily: fonts.regular, fontSize: 12, lineHeight: 18 }, selectedCopy: { color: colors.info, fontFamily: fonts.medium, fontSize: 12 }, error: { color: colors.danger, fontFamily: fonts.regular, fontSize: 12, lineHeight: 18 }, options: { gap: spacing.xs, maxHeight: 260 }, option: { minHeight: 48, justifyContent: "center", padding: spacing.sm, borderRadius: radii.control, borderWidth: 1, borderColor: colors.border }, optionSelected: { backgroundColor: colors.midnight, borderColor: colors.midnight }, optionTitle: { color: colors.ink, fontFamily: fonts.semibold, fontSize: 13 }, optionTitleSelected: { color: colors.surface }, optionCopy: { color: colors.inkMuted, fontFamily: fonts.regular, fontSize: 11 }, actions: { flexDirection: "row", gap: spacing.sm }, action: { flex: 1 } });
