import { apiClient } from "../../api/client";
import { createKnowledgeApi } from "../../../../shared/knowledge/knowledgeApi";
export * from "../../../../shared/knowledge/knowledgeApi";

export const {
  listKnowledgeItems,
  getKnowledgeItem,
  getKnowledgeHistory,
  getKnowledgeSection,
  updateKnowledgeSection,
  createKnowledgeRevision,
  activateKnowledgeRevision,
  deactivateKnowledgeItem,
  duplicateKnowledgeItem,
  listKnowledgeBaskets,
  createKnowledgeBasket,
  updateKnowledgeBasket,
  getKnowledgeBasketDeletionImpact,
  permanentlyDeleteKnowledgeBasket,
  listKnowledgeMainLines,
  createKnowledgeMainLine,
  updateKnowledgeMainLine,
  permanentlyDeleteKnowledgeMainLine,
  listKnowledgeMasters,
  listKnowledgeSurfaces,
  createKnowledgeSurface,
  updateKnowledgeSurface,
  createKnowledgeMaster,
  updateKnowledgeMaster,
  archiveKnowledgeMaster,
  previewKnowledge,
  resolveKnowledgeContext,
  listKnowledgeSubBaskets,
  createKnowledgeSubBasket,
  updateKnowledgeSubBasket,
  getKnowledgeBasketQuality,
  getKnowledgeSubBasketDeletionImpact,
  permanentlyDeleteKnowledgeSubBasket,
  listKnowledgeQualityControlOptions,
  createKnowledgeQualityControlOption,
  updateKnowledgeBasketQuality
} = createKnowledgeApi(apiClient);
