import { MAX_FINANCE_AMOUNT_PAISE } from "../domain/project-finance.js";

const ref = (name: string) => ({ $ref: `#/components/schemas/${name}` });
const object = (properties: Record<string, unknown>, required = Object.keys(properties)) =>
  ({ type: "object", additionalProperties: false, required, properties });
const id = { type: "string", minLength: 1, maxLength: 500 };
const paise = { type: "integer", minimum: 0, maximum: MAX_FINANCE_AMOUNT_PAISE };
const quantity = { type: "integer", minimum: 1, maximum: 1_000_000_000 };
const bps = { type: "integer", minimum: 0, maximum: 10_000 };
const version = { type: "integer", minimum: 1, maximum: Number.MAX_SAFE_INTEGER - 1 };
const digest = { type: "string", pattern: "^[a-f0-9]{64}$" };
const key = { type: "string", pattern: "^[A-Za-z0-9_-]{8,128}$" };
const date = { type: "string", format: "date" };
const totals = object({ netPaise: paise, gstPaise: paise, totalPaise: paise });
const milestoneReviewers = { type: "array", minItems: 5, maxItems: 5, items: object({
  id: { type: "string", enum: ["advance", "mobilisation", "progress_50", "progress_85", "final"] },
  reviewerSlots: { type: "array", uniqueItems: true, maxItems: 4,
    items: { type: "string", enum: ["program_manager", "designer", "procurement", "finance_head"] } }
}) };
const milestone = object({ id: { type: "string", enum: ["advance", "mobilisation", "progress_50", "progress_85", "final"] },
  name: { type: "string" }, basisPoints: bps, amountPaise: paise,
  reviewerSlots: { type: "array", uniqueItems: true,
    items: { type: "string", enum: ["program_manager", "designer", "procurement", "finance_head"] } }
}, ["id", "name", "basisPoints", "amountPaise"]);
const source = object({ estimateId: id, estimateVersion: version, estimateReviewRoundId: { ...id, nullable: true } });
const json = (name: string) => ({ required: true, content: { "application/json": { schema: ref(name) } } });
const basketRoot = "/procurement/projects/:projectId/baskets";
const basketDetail = `${basketRoot}/:basketId`;
const enquiryRoot = `${basketDetail}/enquiries`;
const enquiryDetail = `${enquiryRoot}/:enquiryId`;
const historyRoot = `${enquiryDetail}/history`;
const historyDetail = `${historyRoot}/:revisionId`;
const awardRoot = `${enquiryDetail}/awards`;
const awardDetail = `${awardRoot}/:awardId`;
const classification = { type: "string", enum: ["standard", "special"] };
const standardCost = object({ totalPaise: { ...paise, nullable: true }, complete: { type: "boolean" },
  provisional: { type: "boolean" }, pricedLineCount: { type: "integer", minimum: 0 } });
const standardLineCost = object({ state: { type: "string", enum: ["suggested", "observed_unverified", "saved", "unavailable"] },
  mode: { type: "string", enum: ["pmc", "sub_vendor", "in_house"], nullable: true },
  calculationQuantity: { type: "string", nullable: true },
  baseRates: { type: "array", items: object({ scope: { type: "string", enum: ["pmc", "sub_vendor", "in_house_labor", "in_house_material"] },
    ratePaise: paise }) }, baseCostPaise: { ...paise, nullable: true }, adjustedCostPaise: { ...paise, nullable: true },
  issues: { type: "array", items: ref("ProjectPurchaseOrderModeIssue") } });
const basketSummary = { id, name: { type: "string" }, classification,
  automaticSubVendor: { type: "boolean" }, boqReady: { type: "boolean" },
  standardCost: { ...standardCost, nullable: true },
  includedLineCount: { type: "integer", minimum: 0 }, readyLineCount: { type: "integer", minimum: 0 },
  approvedEstimatePaise: paise, baseCostPaise: paise, adjustedCostPaise: paise,
  workingTotalPaise: paise, workingTotalComplete: { type: "boolean" },
  committedNetPaise: paise, state: { type: "string", enum: ["ready", "partial", "unavailable"] } };
const basketLine = object({ sourceLineItemKey: id, roomId: { ...id, nullable: true }, roomName: { type: "string" },
  subBasketId: { ...id, nullable: true }, subBasketName: { type: "string", nullable: true },
  mainLineId: { ...id, nullable: true }, mainLineName: { type: "string", nullable: true },
  approvedQuantity: { type: "string" }, approvedUnit: { type: "string" },
  approvedAmountPaise: { ...paise, nullable: true }, included: { type: "boolean" },
  source: { type: "string", enum: ["configuration", "legacy"] },
  baseUnitRatePaise: { ...paise, nullable: true },
  projectRate: object({ version: { type: "integer", minimum: 0 }, overridePaise: { ...paise, nullable: true } }),
  mode: { ...ref("ProjectPurchaseOrderModeResolution"), nullable: true },
  standardCost: { ...standardLineCost, nullable: true } });

export const PROCUREMENT_BASKET_TENDER_SCHEMAS = {
  ProcurementBasketSummary: object(basketSummary),
  ProcurementBasketList: object({ projectId: id, estimateSource: source,
    baskets: { type: "array", items: ref("ProcurementBasketSummary") } }),
  ProcurementBasketDetail: object({ ...basketSummary, projectId: id, estimateSource: source,
    preparationDigest: digest, lines: { type: "array", items: basketLine } }),
  ProcurementBasketBoqLineInput: object({ sourceLineItemKey: id,
    description: { type: "string", minLength: 1, maxLength: 2_000 }, quantityMilliUnits: quantity,
    scopeType: { type: "string", enum: ["supply", "execution", "supply_and_execution"] },
    targetDate: date, deliveryLocation: { type: "string", minLength: 1, maxLength: 500 } }, ["sourceLineItemKey"]),
  ProcurementBasketEnquiryCreate: object({ expectedPreparationDigest: digest, idempotencyKey: key,
    lines: { type: "array", minItems: 1, maxItems: 100, items: ref("ProcurementBasketBoqLineInput") } }),
  ProcurementBasketEnquiryUpdate: object({ expectedVersion: version, expectedPreparationDigest: digest,
    idempotencyKey: key, lines: { type: "array", minItems: 1, maxItems: 100, items: ref("ProcurementBasketBoqLineInput") } }),
  ProcurementBasketVendorSelection: { oneOf: [
    object({ kind: { type: "string", enum: ["vendors"] }, vendorIds: { type: "array", minItems: 1,
      maxItems: 5_000, uniqueItems: true, items: id } }),
    object({ kind: { type: "string", enum: ["all_eligible"] }, excludedVendorIds: { type: "array",
      maxItems: 5_000, uniqueItems: true, items: id } }, ["kind"])
  ] },
  ProcurementBasketDispatch: { ...object({ expectedVersion: version, expectedPreparationDigest: digest,
    idempotencyKey: key, vendorIds: { type: "array", minItems: 1, maxItems: 5_000,
      uniqueItems: true, items: id }, selection: ref("ProcurementBasketVendorSelection") },
    ["expectedVersion", "expectedPreparationDigest", "idempotencyKey"]),
    oneOf: [{ required: ["vendorIds"] }, { required: ["selection"] }] },
  ProcurementBasketInvitationBatchPreviewInput: object({ expectedVersion: version,
    boqRevisionId: id, boqDigest: digest, selection: ref("ProcurementBasketVendorSelection") }),
  ProcurementBasketInvitationBatchSubmitInput: object({ expectedVersion: version,
    boqRevisionId: id, boqDigest: digest, selection: ref("ProcurementBasketVendorSelection"),
    idempotencyKey: key, counterofferReason: { type: "string", minLength: 10, maxLength: 2_000 } },
    ["expectedVersion", "boqRevisionId", "boqDigest", "selection", "idempotencyKey"]),
  ProcurementBasketInvitationBatchPreview: object({ enquiryId: id, enquiryVersion: version,
    boqRevisionId: id, boqDigest: digest, selectedCount: { type: "integer", minimum: 1 },
    requiresReason: { type: "boolean" }, actions: { type: "array", minItems: 1,
      items: object({ vendorId: id, vendorName: { type: "string" }, action: { type: "string",
        enum: ["first_invitation", "retry", "updated_bid_request", "already_invited"] },
        invitationStatus: { type: "string", nullable: true }, priorBidId: { ...id, nullable: true } }) } }),
  ProcurementBasketInvitationBatchResult: object({ enquiry: ref("ProcurementBasketEnquiry"),
    selectedCount: { type: "integer", minimum: 1 }, results: { type: "array", minItems: 1,
      items: object({ vendorId: id, action: { type: "string",
        enum: ["first_invitation", "retry", "updated_bid_request", "already_invited"] },
        status: { type: "string", enum: ["sent", "failed", "pending", "consumed", "expired",
          "superseded", "revoked", "already_invited"] }, invitationId: { ...id, nullable: true } }) } }),
  ProcurementBasketResendInvitation: object({ expectedVersion: version, vendorId: id, idempotencyKey: key }),
  ProcurementBasketWhatsAppShareIntent: { type: "object", additionalProperties: false, properties: {} },
  ProcurementBasketWhatsAppShareResult: object({ available: { type: "boolean" },
    shareUrl: { type: "string", nullable: true }, blocker: { type: "string", nullable: true },
    expiresAt: { type: "string", format: "date-time", nullable: true } }),
  ProcurementBasketCounteroffer: object({ expectedVersion: version, vendorId: id, idempotencyKey: key,
    reason: { type: "string", minLength: 10, maxLength: 2_000 }, targetNetPaise: { ...paise, minimum: 1, nullable: true } },
    ["expectedVersion", "vendorId", "idempotencyKey", "reason"]),
  ProcurementBasketEnquiry: { type: "object", additionalProperties: true,
    required: ["id", "projectId", "mainBasketId", "version", "status", "boqRevisionId", "vendorScopeCurrent", "lines", "invitations", "bidCount", "awardId"],
    properties: { id, projectId: id, mainBasketId: id, version, status: { type: "string", enum: ["draft", "sent", "award_pending", "issued", "cancelled"] },
      estimateSource: source, preparationDigest: digest, vendorScopeCurrent: { type: "boolean", nullable: true },
      boqRevisionId: { ...id, nullable: true }, boqDigest: { ...digest, nullable: true },
      lines: { type: "array", items: { type: "object", additionalProperties: true } },
      invitations: { type: "array", items: { type: "object", additionalProperties: true } },
      bidCount: { type: "integer", minimum: 0 }, awardId: { ...id, nullable: true } } },
  ProcurementBasketEnquiryList: { type: "array", items: ref("ProcurementBasketEnquiry") },
  ProcurementBasketBoqHistoryPage: object({ enquiryId: id, currentBoqRevisionId: { ...id, nullable: true },
    revisions: { type: "array", maxItems: 20, items: object({ id, revision: version,
      sentAt: { type: "string", format: "date-time" }, boqDigest: digest,
      lineCount: { type: "integer", minimum: 1, maximum: 100 },
      bidCount: { type: "integer", minimum: 0 }, counterofferCount: { type: "integer", minimum: 0 } }) },
    nextBeforeRevision: { ...version, nullable: true } }),
  ProcurementBasketBoqHistoryDetail: object({ enquiryId: id, canAward: { type: "boolean", enum: [false] },
    boq: object({ id, revision: version, sentAt: { type: "string", format: "date-time" }, digest,
      lines: { type: "array", minItems: 1, maxItems: 100,
        items: { type: "object", additionalProperties: true } } }),
    bids: { type: "array", maxItems: 50, items: { type: "object", additionalProperties: true } },
    bidTotal: { type: "integer", minimum: 0 },
    counteroffers: { type: "array", maxItems: 50, items: { type: "object", additionalProperties: true } },
    counterofferTotal: { type: "integer", minimum: 0 } }),
  ProcurementBasketPublicInspectInput: object({ token: { type: "string", pattern: "^[A-Za-z0-9_-]{43}$" } }),
  ProcurementBasketPublicBoq: object({ projectName: { type: "string" }, basketName: { type: "string" },
    expiresAt: { type: "string", format: "date-time" },
    lines: { type: "array", items: object({ id, description: { type: "string" }, quantityMilliUnits: quantity,
      uomCode: { type: "string" }, approvedQuantity: { type: "string" },
      approvedUnit: { type: "string", nullable: true },
      approvedQuoteAmountPaise: { ...paise, nullable: true },
      scopeType: { type: "string" }, targetDate: date,
      deliveryLocation: { type: "string" } }, ["id", "description", "quantityMilliUnits", "uomCode",
      "approvedQuantity", "approvedUnit", "approvedQuoteAmountPaise"]) } }),
  ProcurementBasketPublicSubmitInput: object({ token: { type: "string", pattern: "^[A-Za-z0-9_-]{43}$" },
    idempotencyKey: key, lines: { type: "array", minItems: 1, maxItems: 100,
      items: object({ boqLineId: id, unitPricePaise: { ...paise, minimum: 1 }, gstBasisPoints: bps }) } }),
  ProcurementBasketBidReceipt: object({ bidId: id, submittedAt: { type: "string", format: "date-time" }, totals }),
  ProcurementBasketComparison: { type: "object", additionalProperties: true,
    required: ["enquiryId", "boqRevisionId", "boqDigest", "comparisonDigest", "rows", "averageBidNetPaise",
      "recommendedBidId", "awardId",
      "bidHistory", "bidHistoryHasMore", "counteroffers", "counteroffersHasMore"],
    properties: { enquiryId: id, boqRevisionId: id, boqDigest: digest, comparisonDigest: digest,
      rows: { type: "array", items: { type: "object", additionalProperties: true,
        required: ["bidId", "vendorId", "quoteNetPaise", "officialKpiScoreBps", "priorityRank", "recommended"],
        properties: { bidId: id, vendorId: id, quoteNetPaise: paise,
          officialKpiScoreBps: { ...bps, nullable: true },
          priorityRank: { type: "integer", minimum: 1, nullable: true }, recommended: { type: "boolean" } } } },
      averageBidNetPaise: { ...paise, nullable: true },
      recommendedBidId: { ...id, nullable: true }, awardId: { ...id, nullable: true },
      bidHistory: { type: "array", items: { type: "object", additionalProperties: true } },
      bidHistoryHasMore: { type: "boolean" },
      counteroffers: { type: "array", items: { type: "object", additionalProperties: true } },
      counteroffersHasMore: { type: "boolean" } } },
  ProcurementBasketAwardPreviewInput: object({ bidId: id, advanceBasisPoints: bps,
    designerId: { ...id, nullable: true }, milestoneReviewers }, ["bidId", "advanceBasisPoints"]),
  ProcurementBasketAwardPreview: { type: "object", additionalProperties: true,
    required: ["bidId", "vendorId", "vendorName", "totals", "milestones", "requiredSlots", "budgetOverrideRequired", "designerOptions", "assignedSiteManager", "assignedDesigner", "approverBlockers"],
    properties: { bidId: id, vendorId: id, vendorName: { type: "string" }, totals,
      milestones: { type: "array", items: milestone },
      requiredSlots: { type: "array", items: { type: "string" } }, budgetOverrideRequired: { type: "boolean" },
      assignedSiteManager: { ...object({ id, name: { type: "string" } }), nullable: true },
      assignedDesigner: { ...object({ id, name: { type: "string" } }), nullable: true },
      approverBlockers: { type: "array", items: object({ slot: { type: "string", enum: ["program_manager", "designer"] },
        code: { type: "string" }, message: { type: "string" } }) },
      designerOptions: { type: "array", items: object({ id, name: { type: "string" } }) } } },
  ProcurementBasketAwardCreate: object({ expectedVersion: version, idempotencyKey: key, bidId: id,
    advanceBasisPoints: bps, milestoneReviewers, terms: { type: "string", minLength: 1, maxLength: 4_000 },
    lineTerms: { type: "array", maxItems: 100, items: object({ boqLineId: id,
      scopeType: { type: "string", enum: ["supply", "execution", "supply_and_execution"] },
      targetDate: date, deliveryLocation: { type: "string", minLength: 1, maxLength: 500 } }, ["boqLineId"]) },
    designerId: { ...id, nullable: true }, nonRecommendedReason: { type: "string", minLength: 10, maxLength: 2_000, nullable: true } },
    ["expectedVersion", "idempotencyKey", "bidId", "advanceBasisPoints", "milestoneReviewers"]),
  ProcurementBasketAwardUpdate: object({ expectedVersion: version, idempotencyKey: key,
    bidId: id, advanceBasisPoints: bps, milestoneReviewers, terms: { type: "string", minLength: 1, maxLength: 4_000 },
    lineTerms: { type: "array", maxItems: 100, items: object({ boqLineId: id,
      scopeType: { type: "string", enum: ["supply", "execution", "supply_and_execution"] },
      targetDate: date, deliveryLocation: { type: "string", minLength: 1, maxLength: 500 } }, ["boqLineId"]) },
    designerId: { ...id, nullable: true }, nonRecommendedReason: { type: "string", minLength: 10, maxLength: 2_000, nullable: true } },
    ["expectedVersion", "idempotencyKey", "advanceBasisPoints", "milestoneReviewers"]),
  ProcurementBasketAwardSubmit: object({ expectedVersion: version, idempotencyKey: key,
    autoIssueOnApproval: { type: "boolean" } }),
  ProcurementBasketAwardWithdraw: object({ expectedVersion: version, idempotencyKey: key,
    reason: { type: "string", minLength: 10, maxLength: 2_000 } }),
  ProcurementBasketAwardDecision: object({ expectedVersion: version, proposalRevisionId: id, idempotencyKey: key,
    slot: { type: "string", enum: ["program_manager", "designer", "procurement", "finance_head", "budget_override"] },
    decision: { type: "string", enum: ["approve", "reject"] },
    reason: { type: "string", maxLength: 2_000, nullable: true } },
    ["expectedVersion", "proposalRevisionId", "idempotencyKey", "slot", "decision"]),
  ProcurementBasketAward: { type: "object", additionalProperties: true,
    required: ["id", "enquiryId", "projectId", "version", "status", "requiresRevision", "withdrawal",
      "autoIssueOnApproval", "issueBlocker",
      "proposalRevisionId", "proposal", "approvals", "lines"],
    properties: { id, enquiryId: id, projectId: id, version, status: { type: "string" },
      requiresRevision: { type: "boolean" }, autoIssueOnApproval: { type: "boolean" },
      issueBlocker: { type: "object", nullable: true, additionalProperties: false,
        properties: { code: { type: "string" }, message: { type: "string" } } },
      withdrawal: { type: "object", nullable: true,
        additionalProperties: true }, proposalRevisionId: id,
      proposal: { type: "object", additionalProperties: true,
        properties: { milestones: { type: "array", items: milestone } } },
      approvals: { type: "array", items: { type: "object", additionalProperties: true } },
      lines: { type: "array", items: { type: "object", additionalProperties: true } } } },
  ProcurementBasketApprovalQueue: { type: "array", items: { type: "object", additionalProperties: true } },
  ProcurementBasketIssueInput: object({ expectedVersion: version, idempotencyKey: key }),
  ProcurementBasketIssueResult: object({ awardId: id, purchaseOrderId: id, orderNumber: { type: "string" }, status: { type: "string", enum: ["issued"] } })
};

export const PROCUREMENT_BASKET_TENDER_REQUESTS = {
  [`POST ${enquiryRoot}`]: json("ProcurementBasketEnquiryCreate"),
  [`PUT ${enquiryDetail}`]: json("ProcurementBasketEnquiryUpdate"),
  [`POST ${enquiryDetail}/dispatch`]: json("ProcurementBasketDispatch"),
  [`POST ${enquiryDetail}/invitation-batches/preview`]: json("ProcurementBasketInvitationBatchPreviewInput"),
  [`POST ${enquiryDetail}/invitation-batches`]: json("ProcurementBasketInvitationBatchSubmitInput"),
  [`POST ${enquiryDetail}/resend-invitation`]: json("ProcurementBasketResendInvitation"),
  [`POST ${enquiryDetail}/invitations/:vendorId/whatsapp-share-intent`]: json("ProcurementBasketWhatsAppShareIntent"),
  [`POST ${enquiryDetail}/counteroffers`]: json("ProcurementBasketCounteroffer"),
  [`POST ${enquiryDetail}/award-preview`]: json("ProcurementBasketAwardPreviewInput"),
  [`POST ${awardRoot}`]: json("ProcurementBasketAwardCreate"),
  [`PUT ${awardDetail}`]: json("ProcurementBasketAwardUpdate"),
  [`POST ${awardDetail}/submit`]: json("ProcurementBasketAwardSubmit"),
  [`POST ${awardDetail}/withdraw`]: json("ProcurementBasketAwardWithdraw"),
  [`POST ${awardDetail}/issue`]: json("ProcurementBasketIssueInput"),
  "POST /work-order-approvals/:awardId/decision": json("ProcurementBasketAwardDecision"),
  "POST /vendor-boq/inspect": json("ProcurementBasketPublicInspectInput"),
  "POST /vendor-boq/submit": json("ProcurementBasketPublicSubmitInput")
};
export const PROCUREMENT_BASKET_TENDER_RESPONSES = {
  [`GET ${basketRoot}`]: "ProcurementBasketList",
  [`GET ${basketDetail}`]: "ProcurementBasketDetail",
  [`GET ${enquiryRoot}`]: "ProcurementBasketEnquiryList",
  [`POST ${enquiryRoot}`]: "ProcurementBasketEnquiry",
  [`GET ${enquiryDetail}`]: "ProcurementBasketEnquiry",
  [`GET ${historyRoot}`]: "ProcurementBasketBoqHistoryPage",
  [`GET ${historyDetail}`]: "ProcurementBasketBoqHistoryDetail",
  [`PUT ${enquiryDetail}`]: "ProcurementBasketEnquiry",
  [`POST ${enquiryDetail}/dispatch`]: "ProcurementBasketEnquiry",
  [`POST ${enquiryDetail}/invitation-batches/preview`]: "ProcurementBasketInvitationBatchPreview",
  [`POST ${enquiryDetail}/invitation-batches`]: "ProcurementBasketInvitationBatchResult",
  [`POST ${enquiryDetail}/resend-invitation`]: "ProcurementBasketEnquiry",
  [`POST ${enquiryDetail}/invitations/:vendorId/whatsapp-share-intent`]: "ProcurementBasketWhatsAppShareResult",
  [`POST ${enquiryDetail}/counteroffers`]: "ProcurementBasketEnquiry",
  [`GET ${enquiryDetail}/comparison`]: "ProcurementBasketComparison",
  [`POST ${enquiryDetail}/award-preview`]: "ProcurementBasketAwardPreview",
  [`POST ${awardRoot}`]: "ProcurementBasketAward",
  [`GET ${awardDetail}`]: "ProcurementBasketAward",
  [`PUT ${awardDetail}`]: "ProcurementBasketAward",
  [`POST ${awardDetail}/submit`]: "ProcurementBasketAward",
  [`POST ${awardDetail}/withdraw`]: "ProcurementBasketAward",
  [`POST ${awardDetail}/issue`]: "ProcurementBasketIssueResult",
  "GET /work-order-approvals": "ProcurementBasketApprovalQueue",
  "GET /work-order-approvals/:awardId": "ProcurementBasketAward",
  "POST /work-order-approvals/:awardId/decision": "ProcurementBasketAward",
  "POST /vendor-boq/inspect": "ProcurementBasketPublicBoq",
  "POST /vendor-boq/submit": "ProcurementBasketBidReceipt"
};
