import { MAX_FINANCE_AMOUNT_PAISE } from "../domain/project-finance.js";

const id = { type: "string", minLength: 1, maxLength: 500 };
const paise = { type: "integer", minimum: 0, maximum: MAX_FINANCE_AMOUNT_PAISE };
const city = { type: "object", additionalProperties: false, required: ["name", "key"],
  properties: { name: { type: "string" }, key: { type: "string" } } };
const json = (name: string) => ({ required: true,
  content: { "application/json": { schema: { $ref: `#/components/schemas/${name}` } } } });
const manager = { type: "object", additionalProperties: false, required: ["id", "name", "email"],
  properties: { id, name: { type: "string" }, email: { type: "string", format: "email" } } };

export const PROCUREMENT_BASKET_OPERATION_SCHEMAS = {
  ProcurementBasketBaseRateSave: { type: "object", additionalProperties: false,
    required: ["sourceLineItemKey", "baseRatePaise", "expectedVersion", "expectedEstimateSource",
      "expectedPreparationDigest", "idempotencyKey"],
    properties: { sourceLineItemKey: id, baseRatePaise: { ...paise, nullable: true },
      expectedVersion: { type: "integer", minimum: 0, maximum: Number.MAX_SAFE_INTEGER - 1 },
      expectedEstimateSource: { type: "object", additionalProperties: false,
        required: ["estimateId", "estimateVersion", "estimateReviewRoundId"],
        properties: { estimateId: id, estimateVersion: { type: "integer", minimum: 1 },
          estimateReviewRoundId: { ...id, nullable: true } } },
      expectedPreparationDigest: { type: "string", pattern: "^[a-f0-9]{64}$" },
      idempotencyKey: { type: "string", pattern: "^[A-Za-z0-9_-]{8,128}$" } } },
  ProcurementBasketBaseRateSaved: { type: "object", additionalProperties: false,
    required: ["projectId", "mainBasketId", "estimateSource", "sourceLineItemKey", "projectRate"],
    properties: { projectId: id, mainBasketId: id, sourceLineItemKey: id,
      estimateSource: { type: "object", additionalProperties: false,
        required: ["estimateId", "estimateVersion", "estimateReviewRoundId"],
        properties: { estimateId: id, estimateVersion: { type: "integer", minimum: 1 },
          estimateReviewRoundId: { ...id, nullable: true } } },
      projectRate: { type: "object", additionalProperties: false,
        required: ["version", "overridePaise"],
        properties: { version: { type: "integer", minimum: 1 }, overridePaise: { ...paise, nullable: true } } } } },
  ProcurementProjectIdentity: { type: "object", additionalProperties: false,
    required: ["projectId", "city", "programManagerId", "version"],
    properties: { projectId: id, city: { ...city, nullable: true }, programManagerId: { ...id, nullable: true },
      version: { type: "integer", minimum: 1 } } },
  ProcurementProjectIdentityUpdate: { type: "object", additionalProperties: false,
    required: ["expectedVersion"],
    anyOf: [{ required: ["cityName"] }, { required: ["programManagerId"] }],
    properties: { expectedVersion: { type: "integer", minimum: 1 },
      cityName: { type: "string", minLength: 1, maxLength: 120, nullable: true },
      programManagerId: { ...id, nullable: true } } },
  ProgramManagerOptions: { type: "object", additionalProperties: false,
    required: ["items", "total", "limit", "offset"],
    properties: { items: { type: "array", items: manager }, total: { type: "integer", minimum: 0 },
      limit: { type: "integer", minimum: 1, maximum: 50 }, offset: { type: "integer", minimum: 0 } } },
  ProcurementVendorCityUpdate: { type: "object", additionalProperties: false,
    required: ["expectedVersion", "cityName"],
    properties: { expectedVersion: { type: "integer", minimum: 0 },
      cityName: { type: "string", minLength: 1, maxLength: 120, nullable: true } } },
  ProcurementVendorCity: { type: "object", additionalProperties: false,
    required: ["vendorId", "city", "version"],
    properties: { vendorId: id, city: { ...city, nullable: true }, version: { type: "integer", minimum: 0 } } },
  ProcurementBasketVendorCandidates: { type: "object", additionalProperties: false,
    required: ["projectCity", "items", "matchingVendorCount", "blockedReasonCounts", "total", "limit", "offset"],
    properties: { projectCity: { ...city, nullable: true },
      items: { type: "array", items: { type: "object", additionalProperties: false,
        required: ["vendorId", "code", "name", "contactEmail", "kpiScoreBps", "city", "cityVersion", "cityMatch", "eligible", "blockers"],
        properties: { vendorId: id, code: { type: "string" }, name: { type: "string" },
          contactEmail: { type: "string", format: "email", nullable: true },
          kpiScoreBps: { type: "integer", minimum: 0, maximum: 10_000, nullable: true },
          city: { ...city, nullable: true }, cityVersion: { type: "integer", minimum: 0 },
          cityMatch: { type: "string", enum: ["same_city", "outside_city", "unknown"] },
          eligible: { type: "boolean" }, blockers: { type: "array", items: { type: "string" } } } } },
      matchingVendorCount: { type: "integer", minimum: 0 },
      blockedReasonCounts: { type: "object", additionalProperties: { type: "integer", minimum: 0 } },
      total: { type: "integer", minimum: 0 }, limit: { type: "integer", minimum: 1 },
      offset: { type: "integer", minimum: 0 } } },
  ProcurementInvoiceAssessmentInput: { type: "object", additionalProperties: false,
    required: ["expectedVersion", "idempotencyKey", "invoiceNumber", "invoiceDate",
      "invoiceEvidenceReference", "invoiceTotalPaise", "tdsBasisPaise", "tdsRateBasisPoints",
      "withholdingEffectiveDate", "withholdingRuleReference", "reason"],
    properties: { expectedVersion: { type: "integer", minimum: 0 },
      idempotencyKey: { type: "string", pattern: "^[A-Za-z0-9_-]{8,128}$" },
      invoiceNumber: { type: "string", minLength: 1, maxLength: 120 }, invoiceDate: { type: "string", format: "date" },
      invoiceEvidenceReference: { type: "string", minLength: 4, maxLength: 500 },
      invoiceTotalPaise: { ...paise, minimum: 1 }, tdsBasisPaise: paise,
      tdsRateBasisPoints: { type: "integer", minimum: 0, maximum: 10_000 },
      withholdingEffectiveDate: { type: "string", format: "date" },
      withholdingRuleReference: { type: "string", minLength: 4, maxLength: 500 },
      reason: { type: "string", minLength: 10, maxLength: 2_000 } } },
  ProcurementInvoiceAssessment: { type: "object", additionalProperties: false,
    required: ["orderId", "version", "revisionId", "invoiceNumber", "invoiceDate", "invoiceEvidenceReference",
      "invoiceTotalPaise", "tdsBasisPaise", "tdsRateBasisPoints", "tdsPaise", "netPayablePaise",
      "withholdingEffectiveDate", "withholdingRuleReference", "reason", "assessedAt", "assessedById"],
    properties: { orderId: id, version: { type: "integer", minimum: 1 }, revisionId: id,
      invoiceNumber: { type: "string" }, invoiceDate: { type: "string", format: "date" },
      invoiceEvidenceReference: { type: "string" }, invoiceTotalPaise: paise, tdsBasisPaise: paise,
      tdsRateBasisPoints: { type: "integer", minimum: 0, maximum: 10_000 }, tdsPaise: paise,
      netPayablePaise: paise, withholdingEffectiveDate: { type: "string", format: "date" },
      withholdingRuleReference: { type: "string" }, reason: { type: "string" },
      assessedAt: { type: "string", format: "date-time" }, assessedById: id } },
  ProcurementInvoiceAssessmentRead: { type: "object", additionalProperties: false,
    required: ["order", "assessment"],
    properties: { order: { type: "object", additionalProperties: false,
      required: ["id", "orderNumber", "projectId", "vendorName", "netPaise", "gstPaise", "totalPaise"],
      properties: { id, orderNumber: { type: "string" }, projectId: id, vendorName: { type: "string" },
        netPaise: paise, gstPaise: paise, totalPaise: paise } },
    assessment: { $ref: "#/components/schemas/ProcurementInvoiceAssessment", nullable: true } } },
  ProcurementFinanceWorkOrderPage: { type: "object", additionalProperties: false,
    required: ["items", "total", "limit", "offset"],
    properties: { items: { type: "array", items: { type: "object", additionalProperties: false,
      required: ["id", "orderNumber", "vendorName", "netPaise", "gstPaise", "totalPaise", "approvedAt", "assessmentStatus", "assessmentVersion"],
      properties: { id, orderNumber: { type: "string" }, vendorName: { type: "string" },
        netPaise: paise, gstPaise: paise, totalPaise: paise,
        approvedAt: { type: "string", format: "date-time" },
        assessmentStatus: { type: "string", enum: ["pending", "reviewed"] },
        assessmentVersion: { type: "integer", minimum: 0 } } } },
      total: { type: "integer", minimum: 0 }, limit: { type: "integer", minimum: 1 },
      offset: { type: "integer", minimum: 0 } } },
  ProcurementBasketPackageMonitor: { type: "object", additionalProperties: false,
    required: ["award", "order", "boqLines", "site", "finance", "vendorAlerts"],
    properties: { award: { type: "object", additionalProperties: true },
      order: { type: "object", additionalProperties: true },
      boqLines: { type: "array", items: { type: "object", additionalProperties: true } },
      site: { type: "object", additionalProperties: true },
      finance: { type: "object", additionalProperties: true,
        properties: { paidPaise: { ...paise, nullable: true },
          recordedCostPaise: { ...paise, nullable: true } } },
      vendorAlerts: { type: "array", items: { type: "object", additionalProperties: true } } } },
  ProcurementBasketShareIntent: { type: "object", additionalProperties: false,
    required: ["available", "shareUrl", "blocker"],
    properties: { available: { type: "boolean" }, shareUrl: { type: "string", nullable: true },
      blocker: { type: "string", nullable: true } } }
};

export const PROCUREMENT_BASKET_OPERATION_REQUESTS = {
  "PUT /procurement/projects/:projectId/baskets/:basketId/base-rate": json("ProcurementBasketBaseRateSave"),
  "PATCH /admin/projects/:projectId/procurement-identity": json("ProcurementProjectIdentityUpdate"),
  "PUT /procurement/vendors/:vendorId/service-city": json("ProcurementVendorCityUpdate"),
  "POST /finance/work-orders/:orderId/invoice-assessment": json("ProcurementInvoiceAssessmentInput")
};

export const PROCUREMENT_BASKET_OPERATION_RESPONSES = {
  "PUT /procurement/projects/:projectId/baskets/:basketId/base-rate": "ProcurementBasketBaseRateSaved",
  "GET /admin/program-managers": "ProgramManagerOptions",
  "GET /admin/projects/:projectId/procurement-identity": "ProcurementProjectIdentity",
  "PATCH /admin/projects/:projectId/procurement-identity": "ProcurementProjectIdentity",
  "PUT /procurement/vendors/:vendorId/service-city": "ProcurementVendorCity",
  "GET /procurement/projects/:projectId/baskets/:basketId/vendor-candidates": "ProcurementBasketVendorCandidates",
  "GET /finance/work-orders/:orderId/invoice-assessment": "ProcurementInvoiceAssessmentRead",
  "GET /finance/projects/:projectId/work-orders": "ProcurementFinanceWorkOrderPage",
  "POST /finance/work-orders/:orderId/invoice-assessment": "ProcurementInvoiceAssessment",
  "GET /procurement/projects/:projectId/baskets/:basketId/awards/:awardId/monitor": "ProcurementBasketPackageMonitor",
  "POST /procurement/projects/:projectId/baskets/:basketId/awards/:awardId/share-intent": "ProcurementBasketShareIntent"
};

export const PROCUREMENT_BASKET_OPERATION_QUERIES = {
  "GET /finance/projects/:projectId/work-orders": [
    { name: "limit", in: "query", required: false, schema: { type: "integer", minimum: 1, maximum: 100, default: 20 } },
    { name: "offset", in: "query", required: false, schema: { type: "integer", minimum: 0, default: 0 } }
  ],
  "GET /admin/program-managers": [
    { name: "q", in: "query", required: false, schema: { type: "string", maxLength: 120, default: "" } },
    { name: "limit", in: "query", required: false, schema: { type: "integer", minimum: 1, maximum: 50, default: 20 } },
    { name: "offset", in: "query", required: false, schema: { type: "integer", minimum: 0, default: 0 } }
  ],
  "GET /procurement/projects/:projectId/baskets/:basketId/vendor-candidates": [
    { name: "q", in: "query", required: false, schema: { type: "string", maxLength: 120, default: "" } },
    { name: "city", in: "query", required: false, schema: { type: "string", enum: ["all", "same_city", "outside_city", "unknown"], default: "all" } },
    { name: "limit", in: "query", required: false, schema: { type: "integer", minimum: 1, maximum: 100, default: 25 } },
    { name: "offset", in: "query", required: false, schema: { type: "integer", minimum: 0, default: 0 } }
  ]
};
