/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/accept-invitation`; params?: Router.UnknownInputParams; } | { pathname: `/access-denied`; params?: Router.UnknownInputParams; } | { pathname: `/forgot-password`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/more`; params?: Router.UnknownInputParams; } | { pathname: `/reset-password`; params?: Router.UnknownInputParams; } | { pathname: `/sign-in`; params?: Router.UnknownInputParams; } | { pathname: `/startup-recovery`; params?: Router.UnknownInputParams; } | { pathname: `/welcome`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/feature/[featureId]`, params: Router.UnknownInputParams & { featureId: string | number; } } | { pathname: `/record/[featureId]/[recordId]`, params: Router.UnknownInputParams & { featureId: string | number;recordId: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/accept-invitation`; params?: Router.UnknownOutputParams; } | { pathname: `/access-denied`; params?: Router.UnknownOutputParams; } | { pathname: `/forgot-password`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/more`; params?: Router.UnknownOutputParams; } | { pathname: `/reset-password`; params?: Router.UnknownOutputParams; } | { pathname: `/sign-in`; params?: Router.UnknownOutputParams; } | { pathname: `/startup-recovery`; params?: Router.UnknownOutputParams; } | { pathname: `/welcome`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/feature/[featureId]`, params: Router.UnknownOutputParams & { featureId: string; } } | { pathname: `/record/[featureId]/[recordId]`, params: Router.UnknownOutputParams & { featureId: string;recordId: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/accept-invitation${`?${string}` | `#${string}` | ''}` | `/access-denied${`?${string}` | `#${string}` | ''}` | `/forgot-password${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/more${`?${string}` | `#${string}` | ''}` | `/reset-password${`?${string}` | `#${string}` | ''}` | `/sign-in${`?${string}` | `#${string}` | ''}` | `/startup-recovery${`?${string}` | `#${string}` | ''}` | `/welcome${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/accept-invitation`; params?: Router.UnknownInputParams; } | { pathname: `/access-denied`; params?: Router.UnknownInputParams; } | { pathname: `/forgot-password`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/more`; params?: Router.UnknownInputParams; } | { pathname: `/reset-password`; params?: Router.UnknownInputParams; } | { pathname: `/sign-in`; params?: Router.UnknownInputParams; } | { pathname: `/startup-recovery`; params?: Router.UnknownInputParams; } | { pathname: `/welcome`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | `/feature/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/record/${Router.SingleRoutePart<T>}/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `/feature/[featureId]`, params: Router.UnknownInputParams & { featureId: string | number; } } | { pathname: `/record/[featureId]/[recordId]`, params: Router.UnknownInputParams & { featureId: string | number;recordId: string | number; } };
    }
  }
}
