import { useMutation, useQuery } from "@tanstack/react-query";
import { useState } from "react";
import { Pressable, StyleSheet, Text, View } from "react-native";

import type { AuthenticatedSession } from "../../contracts/session";
import { ApiError } from "../../core/http/apiClient";
import { privateQueryKey } from "../../core/query/queryClient";
import { useInvalidateEvent } from "../../core/query/useInvalidation";
import { canPerformOperation } from "../../core/session/operationCapabilities";
import { pickDocument, TransferHttpError, type SelectedAsset } from "../../platform/files";
import { useConfiguredRuntime } from "../../runtime/RuntimeProvider";
import { BrandLoader } from "../../ui/brand";
import { Button, Field, StateView } from "../../ui/primitives";
import { colors, fonts, radii, spacing } from "../../ui/tokens";
import { extractionLabel, isEditableExtraction, parseCropInput } from "./designModel";

const FILE_POLICY = { acceptedMimeTypes: ["application/pdf", "image/png", "image/jpeg", "image/webp", "application/octet-stream"], maxBytes: 25 * 1024 * 1024 } as const;
type DataRecord = Record<string, unknown>;
function isRecord(value: unknown): value is DataRecord { return typeof value === "object" && value !== null && !Array.isArray(value); }
function recordArray(value: unknown, key?: string): readonly DataRecord[] { const source = key && isRecord(value) ? value[key] : value; return Array.isArray(source) ? source.filter(isRecord) : []; }
function message(cause: unknown, fallback: string): string { return cause instanceof ApiError || cause instanceof TransferHttpError ? cause.message : cause instanceof Error ? cause.message : fallback; }

export function DesignUploadAction({ taskId, session, onUploaded }: { readonly taskId: string; readonly session: AuthenticatedSession; readonly onUploaded?: () => void }) {
  const context = useConfiguredRuntime(); const invalidate = useInvalidateEvent();
  const [asset, setAsset] = useState<SelectedAsset | null>(null); const [pending, setPending] = useState(false); const [progress, setProgress] = useState<number | null>(null); const [error, setError] = useState<string | null>(null);
  const choose = async () => { try { const result = await pickDocument(FILE_POLICY); if (result.status === "selected") { setAsset(result.asset); setError(null); } } catch (cause) { setError(message(cause, "The design file could not be selected.")); } };
  const upload = async () => { if (!asset) return; setPending(true); setProgress(0); setError(null); try { await context.runtime.transfers.upload({ path: `/tasks/${encodeURIComponent(taskId)}/design-versions`, fileUri: asset.uri, fileName: asset.name, mimeType: asset.mimeType, maxBytes: FILE_POLICY.maxBytes, onProgress: (value) => setProgress(value.fraction) }).result; setAsset(null); setProgress(null); await invalidate("design-workflow-changed"); onUploaded?.(); } catch (cause) { setError(message(cause, "The design could not be uploaded.")); } finally { setPending(false); } };
  if (!canPerformOperation(session, "POST /tasks/:taskId/design-versions")) return null;
  return <View style={styles.actionPanel}><Text style={styles.actionTitle}>Design version</Text><Text style={styles.copy}>PDF, PNG, JPEG or WebP. Maximum 25 MB.</Text><Button label={asset ? asset.name : "Choose design file"} variant="secondary" disabled={pending} onPress={() => void choose()} />{progress !== null ? <Text accessibilityLiveRegion="polite" style={styles.copy}>{progress >= 1 ? "Upload complete. Processing…" : `Uploading ${Math.round(progress * 100)}%`}</Text> : null}{error ? <Text accessibilityLiveRegion="assertive" style={styles.error}>{error}</Text> : null}{asset ? <View style={styles.actions}><View style={styles.action}><Button label="Clear" variant="quiet" disabled={pending} onPress={() => setAsset(null)} /></View><View style={styles.action}><Button label="Upload" loading={pending} onPress={() => void upload()} /></View></View> : null}</View>;
}

function VersionActions({ version, session, refresh }: { readonly version: DataRecord; readonly session: AuthenticatedSession; readonly refresh: () => void }) {
  const context = useConfiguredRuntime(); const invalidate = useInvalidateEvent();
  const id = typeof version.id === "string" ? version.id : null; const [error, setError] = useState<string | null>(null); const [pending, setPending] = useState<string | null>(null);
  if (!id) return null;
  const download = async () => { setPending("download"); setError(null); try { const artifact = await context.runtime.transfers.download({ path: `/design-versions/${encodeURIComponent(id)}/download`, fileName: typeof version.originalFilename === "string" ? version.originalFilename : `design-${id}`, mimeType: typeof version.mimeType === "string" ? version.mimeType : "application/octet-stream", maxBytes: 50 * 1024 * 1024 }).result; await artifact.share(); } catch (cause) { setError(message(cause, "The design could not be downloaded.")); } finally { setPending(null); } };
  const command = async (kind: "retry" | "submit" | "approve" | "reject") => { setPending(kind); setError(null); try { if (kind === "retry") await context.runtime.api.authenticated.post(`/design-versions/${encodeURIComponent(id)}/retry-extraction`); else if (kind === "submit") await context.runtime.api.authenticated.post(`/design-versions/${encodeURIComponent(id)}/submit-sections`); else await context.runtime.api.authenticated.patch(`/design-versions/${encodeURIComponent(id)}/approval`, { approvalStatus: kind === "approve" ? "approved" : "rejected", clientVisible: kind === "approve" }); await invalidate("design-workflow-changed"); refresh(); } catch (cause) { setError(message(cause, "The design action could not be completed.")); } finally { setPending(null); } };
  const status = version.extractionStatus;
  return <View style={styles.compact}><View style={styles.actions}>{canPerformOperation(session, "GET /design-versions/:versionId/download") ? <View style={styles.action}><Button label="Download" variant="secondary" loading={pending === "download"} disabled={pending !== null && pending !== "download"} onPress={() => void download()} /></View> : null}{status === "processing_failed" && canPerformOperation(session, "POST /design-versions/:versionId/retry-extraction") ? <View style={styles.action}><Button label="Retry extraction" loading={pending === "retry"} onPress={() => void command("retry")} /></View> : null}</View>{canPerformOperation(session, "PATCH /design-versions/:versionId/approval") ? <View style={styles.actions}><View style={styles.action}><Button label="Reject" variant="danger" loading={pending === "reject"} onPress={() => void command("reject")} /></View><View style={styles.action}><Button label="Approve" loading={pending === "approve"} onPress={() => void command("approve")} /></View></View> : null}{error ? <Text accessibilityLiveRegion="assertive" style={styles.error}>{error}</Text> : null}<DesignSectionEditor versionId={id} status={status} session={session} onSubmitted={() => void command("submit")} submitPending={pending === "submit"} /></View>;
}

function DesignSectionEditor({ versionId, status, session, onSubmitted, submitPending }: { readonly versionId: string; readonly status: unknown; readonly session: AuthenticatedSession; readonly onSubmitted: () => void; readonly submitPending: boolean }) {
  const context = useConfiguredRuntime(); const invalidate = useInvalidateEvent(); const editable = isEditableExtraction(status);
  const scope = { environmentId: context.environment.environment.id, userId: session.user.id };
  const query = useQuery({ queryKey: privateQueryKey(scope, "design", "sections", versionId), queryFn: ({ signal }) => context.runtime.api.authenticated.get<unknown>(`/design-versions/${encodeURIComponent(versionId)}/sections`, { signal }), enabled: canPerformOperation(session, "GET /design-versions/:versionId/sections") && !["queued", "processing"].includes(String(status)), retry: false });
  const [adding, setAdding] = useState(false); const [pageId, setPageId] = useState(""); const [label, setLabel] = useState(""); const [x, setX] = useState("0"); const [y, setY] = useState("0"); const [width, setWidth] = useState(""); const [height, setHeight] = useState(""); const [error, setError] = useState<string | null>(null);
  const add = useMutation({ mutationFn: async () => { const crop = parseCropInput({ x, y, width, height }); if (!pageId || !label.trim() || !crop) throw new Error("Choose a page, enter a label, and use non-negative integer coordinates with a positive size."); return context.runtime.api.authenticated.post(`/design-versions/${encodeURIComponent(versionId)}/sections`, { sourcePageId: pageId, label: label.trim(), crop }); }, onSuccess: async () => { setAdding(false); setLabel(""); await invalidate("design-workflow-changed"); await query.refetch(); }, onError: (cause) => setError(message(cause, "The section could not be created.")) });
  if (!canPerformOperation(session, "GET /design-versions/:versionId/sections")) return null;
  if (query.isPending) return <BrandLoader label="Loading extracted sections" tone="dark" />;
  if (query.isError) return <Text style={styles.warning}>{query.error instanceof ApiError && query.error.status === 409 ? "Extracted sections are not available yet." : "Extracted sections could not be loaded."}</Text>;
  const pages = recordArray(query.data, "pages"); const sections = recordArray(query.data, "sections");
  return <View style={styles.sectionBlock}><View style={styles.rowBetween}><Text style={styles.actionTitle}>Extracted sections</Text><Text style={styles.status}>{sections.length}</Text></View>{sections.length === 0 ? <Text style={styles.copy}>No section drafts are available.</Text> : sections.map((section, index) => <SectionRow key={typeof section.id === "string" ? section.id : `section-${index}`} section={section} editable={editable} session={session} refresh={() => void query.refetch()} />)}{editable && canPerformOperation(session, "POST /design-versions/:versionId/sections") ? adding ? <View style={styles.actionPanel}><Text style={styles.label}>Source page</Text><View accessibilityRole="radiogroup" style={styles.options}>{pages.map((page, index) => { const id = typeof page.id === "string" ? page.id : ""; return <Pressable key={id || index} accessibilityRole="radio" accessibilityState={{ selected: pageId === id }} onPress={() => setPageId(id)} style={[styles.option, pageId === id ? styles.selected : null]}><Text style={[styles.optionText, pageId === id ? styles.selectedText : null]}>Page {typeof page.pageNumber === "number" ? page.pageNumber : index + 1}</Text></Pressable>; })}</View><Field label="Section label" value={label} onChangeText={setLabel} /><View style={styles.coordinateRow}><View style={styles.coordinate}><Field label="X" value={x} onChangeText={setX} keyboardType="number-pad" /></View><View style={styles.coordinate}><Field label="Y" value={y} onChangeText={setY} keyboardType="number-pad" /></View></View><View style={styles.coordinateRow}><View style={styles.coordinate}><Field label="Width" value={width} onChangeText={setWidth} keyboardType="number-pad" /></View><View style={styles.coordinate}><Field label="Height" value={height} onChangeText={setHeight} keyboardType="number-pad" /></View></View>{error ? <Text style={styles.error}>{error}</Text> : null}<View style={styles.actions}><View style={styles.action}><Button label="Cancel" variant="quiet" onPress={() => setAdding(false)} /></View><View style={styles.action}><Button label="Add section" loading={add.isPending} onPress={() => add.mutate()} /></View></View></View> : <Button label="Add manual section" variant="secondary" onPress={() => { setAdding(true); setError(null); }} /> : null}{editable && sections.length > 0 && canPerformOperation(session, "POST /design-versions/:versionId/submit-sections") ? <Button label="Submit sections to Client" loading={submitPending} onPress={onSubmitted} /> : null}</View>;
}

function SectionRow({ section, editable, session, refresh }: { readonly section: DataRecord; readonly editable: boolean; readonly session: AuthenticatedSession; readonly refresh: () => void }) {
  const context = useConfiguredRuntime(); const invalidate = useInvalidateEvent(); const id = typeof section.id === "string" ? section.id : null; const revision = isRecord(section.revision) ? section.revision : {}; const version = typeof revision.revisionNumber === "number" ? revision.revisionNumber : null;
  const [editing, setEditing] = useState(false); const [label, setLabel] = useState(typeof section.label === "string" ? section.label : ""); const [error, setError] = useState<string | null>(null);
  const mutation = useMutation({ mutationFn: async (kind: "edit" | "delete") => { if (!id || !version) throw new Error("This section has no current version."); return kind === "edit" ? context.runtime.api.authenticated.patch(`/design-sections/${encodeURIComponent(id)}`, { version, label: label.trim() }) : context.runtime.api.authenticated.delete(`/design-sections/${encodeURIComponent(id)}`, { version }); }, onSuccess: async () => { setEditing(false); await invalidate("design-workflow-changed"); refresh(); }, onError: (cause) => setError(cause instanceof ApiError && cause.status === 409 ? "This section changed. Refresh and review the current draft." : message(cause, "The section could not be updated.")) });
  return <View style={styles.sectionRow}><Text style={styles.itemTitle}>{typeof section.label === "string" ? section.label : "Untitled section"}</Text><Text style={styles.copy}>Revision {version ?? "—"} · {typeof revision.reviewStatus === "string" ? revision.reviewStatus.replaceAll("_", " ") : "draft"}</Text>{editing ? <View style={styles.compact}><Field label="Section label" value={label} onChangeText={setLabel} />{error ? <Text style={styles.error}>{error}</Text> : null}<View style={styles.actions}><View style={styles.action}><Button label="Cancel" variant="quiet" onPress={() => setEditing(false)} /></View><View style={styles.action}><Button label="Save label" loading={mutation.isPending} disabled={!label.trim()} onPress={() => mutation.mutate("edit")} /></View></View></View> : editable ? <View style={styles.actions}>{canPerformOperation(session, "PATCH /design-sections/:sectionId") ? <View style={styles.action}><Button label="Edit label" variant="quiet" onPress={() => setEditing(true)} /></View> : null}{canPerformOperation(session, "DELETE /design-sections/:sectionId") ? <View style={styles.action}><Button label="Remove" variant="danger" loading={mutation.isPending} onPress={() => mutation.mutate("delete")} /></View> : null}</View> : null}{!editing && error ? <Text style={styles.error}>{error}</Text> : null}</View>;
}

export function DesignVersionWorkspace({ projectId, session }: { readonly projectId: string; readonly session: AuthenticatedSession }) {
  const context = useConfiguredRuntime(); const [expanded, setExpanded] = useState<string | null>(null);
  const scope = { environmentId: context.environment.environment.id, userId: session.user.id };
  const query = useQuery({ queryKey: privateQueryKey(scope, "design", "project", projectId), queryFn: ({ signal }) => context.runtime.api.authenticated.get<unknown>(`/projects/${encodeURIComponent(projectId)}/design-versions?limit=30&offset=0`, { signal }), enabled: canPerformOperation(session, "GET /projects/:projectId/design-versions") });
  if (!canPerformOperation(session, "GET /projects/:projectId/design-versions")) return null;
  if (query.isPending) return <BrandLoader label="Loading design versions" tone="dark" />;
  if (query.isError) return <StateView tone="error" title="Design versions could not be loaded" message="Refresh the project and try again." actionLabel="Retry" onAction={() => void query.refetch()} />;
  const versions = recordArray(query.data, "items");
  return <View style={styles.workspace}><View style={styles.rowBetween}><View><Text style={styles.eyebrow}>DESIGN</Text><Text accessibilityRole="header" style={styles.title}>Design versions</Text></View><Text style={styles.status}>{versions.length}</Text></View>{versions.length === 0 ? <Text style={styles.copy}>Uploaded task designs will appear here.</Text> : versions.map((version, index) => { const id = typeof version.id === "string" ? version.id : `version-${index}`; const open = expanded === id; return <View key={id} style={styles.version}><Pressable accessibilityRole="button" accessibilityState={{ expanded: open }} onPress={() => setExpanded(open ? null : id)} style={styles.rowBetween}><View style={styles.itemCopy}><Text style={styles.itemTitle}>{typeof version.originalFilename === "string" ? version.originalFilename : `Design version ${index + 1}`}</Text><Text style={styles.copy}>Version {typeof version.versionNumber === "number" ? version.versionNumber : "—"} · {typeof version.approvalStatus === "string" ? version.approvalStatus.replaceAll("_", " ") : "draft"}</Text><Text style={styles.copy}>{extractionLabel(version.extractionStatus)}</Text></View><Text style={styles.chevron}>{open ? "−" : "+"}</Text></Pressable>{open ? <VersionActions version={version} session={session} refresh={() => void query.refetch()} /> : null}</View>; })}<Button label="Refresh designs" variant="secondary" onPress={() => void query.refetch()} /></View>;
}

const styles = StyleSheet.create({ workspace: { gap: spacing.md, paddingTop: spacing.md, borderTopWidth: 1, borderTopColor: colors.border }, title: { color: colors.ink, fontFamily: fonts.semibold, fontSize: 20 }, eyebrow: { color: colors.violet, fontFamily: fonts.semibold, fontSize: 11, letterSpacing: 1.2 }, version: { padding: spacing.md, gap: spacing.md, borderRadius: radii.surface, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.surface }, rowBetween: { minHeight: 44, flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: spacing.md }, itemCopy: { flex: 1, gap: 3 }, itemTitle: { color: colors.ink, fontFamily: fonts.semibold, fontSize: 14 }, copy: { color: colors.inkMuted, fontFamily: fonts.regular, fontSize: 12, lineHeight: 18 }, status: { minWidth: 28, color: colors.violet, fontFamily: fonts.semibold, fontSize: 12, textAlign: "center" }, chevron: { color: colors.violet, fontFamily: fonts.semibold, fontSize: 22 }, compact: { gap: spacing.sm }, actionPanel: { padding: spacing.md, gap: spacing.sm, borderRadius: radii.control, backgroundColor: colors.surfaceMuted, borderWidth: 1, borderColor: colors.border }, actionTitle: { color: colors.ink, fontFamily: fonts.semibold, fontSize: 15 }, actions: { flexDirection: "row", flexWrap: "wrap", gap: spacing.sm }, action: { flex: 1, minWidth: 128 }, error: { color: colors.danger, fontFamily: fonts.regular, fontSize: 12, lineHeight: 18 }, warning: { color: colors.warning, fontFamily: fonts.medium, fontSize: 12 }, sectionBlock: { gap: spacing.sm, paddingTop: spacing.sm }, sectionRow: { gap: spacing.xs, padding: spacing.sm, borderRadius: radii.control, backgroundColor: colors.canvas, borderWidth: 1, borderColor: colors.border }, label: { color: colors.ink, fontFamily: fonts.medium, fontSize: 13 }, options: { flexDirection: "row", flexWrap: "wrap", gap: spacing.xs }, option: { minHeight: 44, justifyContent: "center", paddingHorizontal: spacing.md, borderRadius: radii.pill, borderWidth: 1, borderColor: colors.borderStrong }, selected: { backgroundColor: colors.midnight }, optionText: { color: colors.ink, fontFamily: fonts.medium, fontSize: 12 }, selectedText: { color: colors.surface }, coordinateRow: { flexDirection: "row", gap: spacing.sm }, coordinate: { flex: 1 } });
