import { useMutation, useQuery } from "@tanstack/react-query";
import { useRef, useState } from "react";
import { Pressable, StyleSheet, Text, View } from "react-native";

import type { AuthenticatedSession } from "../../contracts/session";
import { ApiError } from "../../core/http/apiClient";
import { privateQueryKey } from "../../core/query/queryClient";
import { useInvalidateEvent } from "../../core/query/useInvalidation";
import { pickDocument, TransferHttpError, type SelectedAsset } from "../../platform/files";
import { useConfiguredRuntime } from "../../runtime/RuntimeProvider";
import { BrandLoader } from "../../ui/brand";
import { Button, Field } from "../../ui/primitives";
import { colors, fonts, radii, spacing } from "../../ui/tokens";
import { createIdempotencyKey } from "../finance/money";
import { actionDateData, isNativeWorkflowAction, workflowActionNeedsDate, workflowActionNeedsNote, type NativeWorkflowAction } from "./workflowModel";

type Row = Record<string, unknown>;
function record(value: unknown): Row | null { return typeof value === "object" && value !== null && !Array.isArray(value) ? value as Row : null; }
function rows(value: unknown): readonly Row[] { return Array.isArray(value) ? value.filter((item): item is Row => record(item) !== null) : []; }
function strings(value: unknown): readonly string[] { return Array.isArray(value) ? value.filter((item): item is string => typeof item === "string") : []; }
function requestMessage(cause: unknown): string { return cause instanceof ApiError || cause instanceof TransferHttpError ? cause.message : cause instanceof Error ? cause.message : "The workflow action could not be saved."; }
const PROOF_POLICY = { acceptedMimeTypes: ["application/pdf", "image/png", "image/jpeg", "image/webp"], maxBytes: 25 * 1024 * 1024 } as const;

function WorkflowActionForm({ projectId, stageId, operational, action, workflow, refresh }: { readonly projectId: string; readonly stageId: string; readonly operational: Row; readonly action: Row; readonly workflow: Row; readonly refresh: () => void }) {
  const context = useConfiguredRuntime(); const invalidate = useInvalidateEvent(); const id = action.id; if (!isNativeWorkflowAction(id)) return null;
  const version = typeof operational.version === "number" ? operational.version : null; const actionId: NativeWorkflowAction = id; const [open, setOpen] = useState(false); const [note, setNote] = useState(""); const [date, setDate] = useState(""); const [designerId, setDesignerId] = useState(""); const [proof, setProof] = useState<SelectedAsset | null>(null); const [error, setError] = useState<string | null>(null); const [progress, setProgress] = useState<number | null>(null); const identity = useRef(createIdempotencyKey());
  const disabledReason = typeof action.disabledReason === "string" ? action.disabledReason : null; const requiresProof = action.requiresProof === true;
  const choose = async () => { try { const result = await pickDocument(PROOF_POLICY); if (result.status === "selected") setProof(result.asset); } catch (cause) { setError(requestMessage(cause)); } };
  const mutation = useMutation({ retry: false, mutationFn: async () => { if (version === null) throw new Error("The workflow version is unavailable. Refresh before continuing."); if (workflowActionNeedsNote(actionId) && !note.trim()) throw new Error("Add the required reason before continuing."); let data = actionDateData(actionId, date); if (data === null) throw new Error("Enter a valid date and time."); if (actionId === "measurement_assign") { if (!designerId) throw new Error("Choose an assigned measurement Designer."); data = { designerId }; } if (actionId === "client_kickoff_complete") { const submitted = record(operational.submittedDocument); if (!submitted || typeof submitted.eventId !== "string") throw new Error("The submitted kickoff document is unavailable. Refresh before continuing."); data = { reviewedDocumentEventId: submitted.eventId }; } if (actionId === "space_planning_complete") { const plan = record(operational.spacePlanning); if (!plan || plan.readyForCompletion !== true || typeof plan.estimateId !== "string" || typeof plan.designPlanVersion !== "number" || typeof plan.reviewRoundId !== "string") throw new Error("The current Design plan approval is not ready for completion."); data = { estimateId: plan.estimateId, designPlanVersion: plan.designPlanVersion, reviewRoundId: plan.reviewRoundId }; } const payload = { expectedVersion: String(version), action: actionId, stageId, idempotencyKey: identity.current, note: note.trim(), data: JSON.stringify(data ?? {}) }; if (requiresProof) { if (!proof) throw new Error("Choose the required supporting document."); setProgress(0); return context.runtime.transfers.upload<{ readonly version: number }>({ path: `/projects/${encodeURIComponent(projectId)}/design-workflow/actions`, fileUri: proof.uri, fileName: proof.name, mimeType: proof.mimeType, maxBytes: PROOF_POLICY.maxBytes, parameters: payload, onProgress: (value) => setProgress(value.fraction) }).result; } return context.runtime.api.authenticated.post<{ readonly version: number }>(`/projects/${encodeURIComponent(projectId)}/design-workflow/actions`, { expectedVersion: version, action: actionId, stageId, idempotencyKey: identity.current, note: note.trim(), data: data ?? {} }); }, onSuccess: async () => { identity.current = createIdempotencyKey(); setOpen(false); setNote(""); setDate(""); setProof(null); setProgress(null); await invalidate("design-workflow-changed"); refresh(); }, onError: (cause) => setError(cause instanceof ApiError && cause.status === 409 ? "The workflow changed. Refresh and review the current action before trying again." : requestMessage(cause)) });
  if (!open) return <View style={styles.actionChoice}><Button label={typeof action.label === "string" ? action.label : actionId.replaceAll("_", " ")} variant="secondary" disabled={Boolean(disabledReason)} onPress={() => { setOpen(true); setError(null); }} />{disabledReason ? <Text style={styles.blocker}>{disabledReason}</Text> : null}</View>;
  const designers = rows(workflow.measurementDesigners);
  return <View style={styles.form}><Text accessibilityRole="header" style={styles.actionTitle}>{typeof action.label === "string" ? action.label : actionId.replaceAll("_", " ")}</Text>{actionId === "internal_kickoff_complete" ? <Text style={styles.copy}>Saving confirms that the design flow has been handed over after initial payment.</Text> : null}{actionId === "client_kickoff_complete" ? <Text style={styles.copy}>Saving confirms that you reviewed the Designer’s submitted kick-off document.</Text> : null}{workflowActionNeedsDate(actionId) ? <Field label={actionId === "internal_kickoff_complete" ? "Meeting conducted at (ISO 8601)" : "Meeting date and time (ISO 8601)"} value={date} onChangeText={setDate} /> : null}{actionId === "measurement_assign" ? <View style={styles.compact}><Text style={styles.label}>Measurement Designer</Text><View accessibilityRole="radiogroup" style={styles.options}>{designers.map((designer) => { const idValue = typeof designer.id === "string" ? designer.id : ""; const selected = idValue === designerId; return <Pressable key={idValue} accessibilityRole="radio" accessibilityState={{ selected }} onPress={() => setDesignerId(idValue)} style={[styles.option, selected ? styles.selected : null]}><Text style={[styles.optionText, selected ? styles.selectedText : null]}>{typeof designer.name === "string" ? designer.name : idValue}</Text></Pressable>; })}</View></View> : null}<Field label={workflowActionNeedsNote(actionId) ? "Reason" : "Note (optional)"} value={note} onChangeText={setNote} multiline />{requiresProof ? <Button label={proof ? proof.name : "Choose supporting document"} variant="secondary" disabled={mutation.isPending} onPress={() => void choose()} /> : null}{progress !== null ? <Text accessibilityLiveRegion="polite" style={styles.copy}>{progress >= 1 ? "Upload complete. Saving…" : `Uploading ${Math.round(progress * 100)}%`}</Text> : null}{error ? <Text accessibilityLiveRegion="assertive" style={styles.error}>{error}</Text> : null}<View style={styles.actions}><View style={styles.action}><Button label="Cancel" variant="quiet" disabled={mutation.isPending} onPress={() => setOpen(false)} /></View><View style={styles.action}><Button label="Save action" loading={mutation.isPending} onPress={() => mutation.mutate()} /></View></View></View>;
}

function InitialPaymentAction({ projectId, payment, refresh }: { readonly projectId: string; readonly payment: Row; readonly refresh: () => void }) {
  const context = useConfiguredRuntime(); const invalidate = useInvalidateEvent(); const [open, setOpen] = useState(false); const [reference, setReference] = useState(""); const [error, setError] = useState<string | null>(null); const identity = useRef(createIdempotencyKey()); const version = typeof payment.version === "number" ? payment.version : null;
  const mutation = useMutation({ retry: false, mutationFn: () => { if (version === null || !reference.trim()) throw new Error("Enter the payment receipt reference."); return context.runtime.api.authenticated.post(`/projects/${encodeURIComponent(projectId)}/design-workflow/actions`, { expectedVersion: version, action: "confirm_initial_payment", idempotencyKey: identity.current, note: reference.trim(), data: {} }); }, onSuccess: async () => { identity.current = createIdempotencyKey(); setOpen(false); setReference(""); await invalidate("design-workflow-changed"); refresh(); }, onError: (cause) => setError(requestMessage(cause)) });
  if (payment.confirmedAt) return <Text style={styles.success}>Initial payment confirmed {new Date(String(payment.confirmedAt)).toLocaleString()}.</Text>;
  if (payment.canConfirm !== true) return <Text style={styles.blocker}>{typeof payment.issue === "string" ? payment.issue : "Initial payment is awaiting confirmation."}</Text>;
  if (!open) return <Button label="Confirm initial payment" variant="secondary" onPress={() => setOpen(true)} />;
  return <View style={styles.form}><Field label="Payment receipt reference" value={reference} onChangeText={setReference} /><Text style={styles.copy}>This records an audited confirmation against the approved estimate source.</Text>{error ? <Text style={styles.error}>{error}</Text> : null}<View style={styles.actions}><View style={styles.action}><Button label="Cancel" variant="quiet" onPress={() => setOpen(false)} /></View><View style={styles.action}><Button label="Confirm payment" loading={mutation.isPending} onPress={() => mutation.mutate()} /></View></View></View>;
}

function History({ projectId, events }: { readonly projectId: string; readonly events: readonly Row[] }) {
  const context = useConfiguredRuntime(); const [busy, setBusy] = useState<string | null>(null); const [error, setError] = useState<string | null>(null);
  const download = async (event: Row, media?: Row) => { const eventId = typeof event.id === "string" ? event.id : null; const mediaId = media && typeof media.id === "string" ? media.id : null; if (!eventId) return; setBusy(mediaId ?? eventId); setError(null); try { const name = media && typeof media.filename === "string" ? media.filename : "workflow-evidence"; const mime = media && typeof media.mimeType === "string" ? media.mimeType : "application/octet-stream"; const path = mediaId ? `/projects/${encodeURIComponent(projectId)}/design-workflow/history/${encodeURIComponent(eventId)}/media/${encodeURIComponent(mediaId)}` : `/projects/${encodeURIComponent(projectId)}/design-workflow/history/${encodeURIComponent(eventId)}/proof`; const artifact = await context.runtime.transfers.download({ path, fileName: name, mimeType: mime, maxBytes: 50 * 1024 * 1024 }).result; await artifact.share(); } catch (cause) { setError(requestMessage(cause)); } finally { setBusy(null); } };
  if (!events.length) return null;
  return <View style={styles.history}><Text style={styles.label}>ACTION HISTORY</Text>{[...events].reverse().map((event, index) => <View key={typeof event.id === "string" ? event.id : index} style={styles.historyRow}><Text style={styles.itemTitle}>{typeof event.action === "string" ? event.action.replaceAll("_", " ") : "Workflow action"}</Text><Text style={styles.copy}>{typeof event.actorName === "string" ? event.actorName : "Lisno user"}{typeof event.at === "string" ? ` · ${new Date(event.at).toLocaleString()}` : ""}</Text>{typeof event.note === "string" && event.note ? <Text style={styles.copy}>{event.note}</Text> : null}{event.proofAvailable === true ? <Button label="Download evidence" variant="quiet" loading={busy === event.id} onPress={() => void download(event)} /> : null}{rows(event.mediaFiles).map((media) => <Button key={String(media.id)} label={`Download ${String(media.filename ?? "media")}`} variant="quiet" loading={busy === media.id} onPress={() => void download(event, media)} />)}</View>)}{error ? <Text style={styles.error}>{error}</Text> : null}</View>;
}

export function WorkflowWorkspace({ projectId, session }: { readonly projectId: string; readonly session: AuthenticatedSession }) {
  const context = useConfiguredRuntime(); const [expanded, setExpanded] = useState<string | null>(null); const scope = { environmentId: context.environment.environment.id, userId: session.user.id };
  const query = useQuery({ queryKey: privateQueryKey(scope, "workflow", "project", projectId), queryFn: ({ signal }) => context.runtime.api.authenticated.get<Row>(`/projects/${encodeURIComponent(projectId)}/design-workflow`, { signal }), enabled: session.authorization.permissions.includes("projects.design_workflow.read") });
  if (!session.authorization.permissions.includes("projects.design_workflow.read")) return null;
  if (query.isPending) return <BrandLoader label="Loading project workflow" tone="dark" />;
  if (query.isError) return <Text style={styles.error}>The project workflow could not be loaded.</Text>;
  const workflow = query.data; const stages = rows(workflow.projectStages); const payment = record(workflow.initialPayment);
  return <View style={styles.workspace}><View><Text style={styles.eyebrow}>WORKFLOW</Text><Text accessibilityRole="header" style={styles.title}>Project journey</Text><Text style={styles.copy}>Stage availability, blockers and timing come directly from Lisno.</Text></View>{payment ? <InitialPaymentAction projectId={projectId} payment={payment} refresh={() => void query.refetch()} /> : null}{stages.map((stage, index) => { const id = typeof stage.id === "string" ? stage.id : `stage-${index}`; const operational = record(stage.operational); const open = expanded === id; return <View key={id} style={styles.stage}><Pressable accessibilityRole="button" accessibilityState={{ expanded: open }} style={styles.stageHeader} onPress={() => setExpanded(open ? null : id)}><View style={styles.itemCopy}><Text style={styles.itemTitle}>{typeof stage.name === "string" ? stage.name : `Stage ${index + 1}`}</Text><Text style={styles.copy}>{operational && typeof operational.status === "string" ? operational.status.replaceAll("_", " ") : "Status unavailable"}{operational && typeof operational.progress === "number" ? ` · ${operational.progress}%` : ""}</Text></View><Text style={styles.chevron}>{open ? "−" : "+"}</Text></Pressable>{open && operational ? <View style={styles.stageBody}>{rows(operational.facts).map((fact, factIndex) => <Text key={factIndex} style={styles.copy}>{String(fact.label ?? "Detail")}: {String(fact.value ?? "Unavailable")}</Text>)}{strings(operational.blockingReasons).map((blocker, blockerIndex) => <Text key={blockerIndex} style={styles.blocker}>{blocker}</Text>)}{rows(operational.availableActions).filter((action) => isNativeWorkflowAction(action.id)).map((action) => <WorkflowActionForm key={String(action.id)} projectId={projectId} stageId={id} operational={operational} action={action} workflow={workflow} refresh={() => void query.refetch()} />)}<History projectId={projectId} events={rows(operational.history)} /></View> : null}</View>; })}<Button label="Refresh workflow" variant="secondary" onPress={() => void query.refetch()} /></View>;
}

const styles = StyleSheet.create({ workspace: { gap: spacing.md, paddingTop: spacing.md, borderTopWidth: 1, borderTopColor: colors.border }, eyebrow: { color: colors.violet, fontFamily: fonts.semibold, fontSize: 11, letterSpacing: 1.2 }, title: { color: colors.ink, fontFamily: fonts.semibold, fontSize: 20 }, stage: { borderRadius: radii.surface, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.surface, overflow: "hidden" }, stageHeader: { minHeight: 68, padding: spacing.md, flexDirection: "row", alignItems: "center", gap: spacing.md }, itemCopy: { flex: 1, gap: 3 }, itemTitle: { color: colors.ink, fontFamily: fonts.semibold, fontSize: 14, textTransform: "capitalize" }, copy: { color: colors.inkMuted, fontFamily: fonts.regular, fontSize: 12, lineHeight: 18 }, chevron: { color: colors.violet, fontFamily: fonts.semibold, fontSize: 22 }, stageBody: { gap: spacing.sm, padding: spacing.md, borderTopWidth: 1, borderTopColor: colors.border }, compact: { gap: spacing.sm }, form: { gap: spacing.sm, padding: spacing.md, borderRadius: radii.control, backgroundColor: colors.surfaceMuted, borderWidth: 1, borderColor: colors.border }, actionChoice: { gap: spacing.xs }, actionTitle: { color: colors.ink, fontFamily: fonts.semibold, fontSize: 15 }, actions: { flexDirection: "row", gap: spacing.sm }, action: { flex: 1 }, blocker: { color: colors.warning, fontFamily: fonts.medium, fontSize: 12, lineHeight: 18 }, success: { color: colors.success, fontFamily: fonts.medium, fontSize: 12, lineHeight: 18 }, error: { color: colors.danger, fontFamily: fonts.regular, fontSize: 12, lineHeight: 18 }, label: { color: colors.inkMuted, fontFamily: fonts.semibold, fontSize: 11, letterSpacing: 0.7 }, options: { gap: spacing.xs }, option: { minHeight: 46, justifyContent: "center", padding: spacing.sm, borderRadius: radii.control, borderWidth: 1, borderColor: colors.borderStrong }, selected: { backgroundColor: colors.midnight }, optionText: { color: colors.ink, fontFamily: fonts.medium, fontSize: 12 }, selectedText: { color: colors.surface }, history: { gap: spacing.sm, paddingTop: spacing.sm }, historyRow: { gap: 3, padding: spacing.sm, borderLeftWidth: 3, borderLeftColor: colors.gold, backgroundColor: colors.canvas } });
