import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Link, useNavigate, useParams } from "react-router-dom";
import { useState } from "react";
import type { LeadActivityType, LeadStage } from "../../api/types";
import { AsyncState } from "../../components/ui/AsyncState";
import "../../styles/estimator-dashboard.css";
import { addLeadActivity, getLead, getLeadActivities, leadKeys, updateLead } from "./leadsApi";

const labels: Record<LeadStage, string> = { new_lead: "New lead", contacted: "Contacted", site_visit: "Site visit", design_meeting: "Design meeting", estimate_in_progress: "Estimate in progress", estimate_sent: "Estimate sent", negotiation: "Negotiation", won: "Won", lost: "Lost" };
export function LeadDetail() {
  const { leadId = "" } = useParams(); const navigate = useNavigate(); const client = useQueryClient(); const [note, setNote] = useState(""); const [type, setType] = useState<LeadActivityType>("note");
  const lead = useQuery({ queryKey: leadKeys.detail(leadId), queryFn: () => getLead(leadId) }); const activities = useQuery({ queryKey: leadKeys.activities(leadId), queryFn: () => getLeadActivities(leadId) });
  const refresh = async () => { await client.invalidateQueries({ queryKey: leadKeys.all }); await client.invalidateQueries({ queryKey: leadKeys.detail(leadId) }); await client.invalidateQueries({ queryKey: leadKeys.activities(leadId) }); };
  const stage = useMutation({ mutationFn: (value: LeadStage) => updateLead(leadId, { stage: value }), onSuccess: refresh });
  const startEstimate = useMutation({ mutationFn: () => updateLead(leadId, { stage: "estimate_in_progress" }), onSuccess: async () => { await refresh(); navigate(`/estimator-sales/leads/${leadId}/estimate`); } });
  const activity = useMutation({ mutationFn: () => addLeadActivity(leadId, { type, note, occurredAt: new Date().toISOString() }), onSuccess: async () => { setNote(""); await refresh(); } });
  if (lead.isPending || activities.isPending) return <AsyncState state="loading" message="Loading lead details…" />;
  if (lead.isError || activities.isError) return <AsyncState state="error" message="We couldn't load this lead." actionLabel="Try again" onAction={() => { void lead.refetch(); void activities.refetch(); }} />;
  const item = lead.data;
  return <section className="lead-detail estimator-dashboard" aria-labelledby="lead-detail-title"><Link to="/estimator-sales" className="lead-detail__back-link"><svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="#D89A3E" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M19 12H5" /><path d="M12 19l-7-7 7-7" /></svg>All leads</Link><header className="workspace-header"><div><p className="eyebrow">{labels[item.stage]}</p><h1 id="lead-detail-title">{item.clientName}</h1><p>{item.projectName} · {item.propertyType} · {item.location}</p></div><label>Lead stage<select aria-label="Lead stage" value={item.stage} onChange={(event) => stage.mutate(event.target.value as LeadStage)}>{Object.entries(labels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label></header><div className="lead-detail__grid"><section><h2>Contact and project</h2><p><strong>{item.clientMobile}</strong> · {item.clientEmail}</p><p>Budget: ₹{item.budgetMin?.toLocaleString() ?? "—"} – ₹{item.budgetMax?.toLocaleString() ?? "—"}</p><p>Next action: <strong>{item.nextAction}</strong></p><section className="lead-estimate-boundary"><h2>Estimate</h2><p>Configure rooms, dimensions and scope. Follow-ups remain available independently.</p><button className="button button--primary" onClick={() => startEstimate.mutate()} disabled={startEstimate.isPending}>{startEstimate.isPending ? "Opening…" : "Start estimate"}</button></section></section><section><h2>Follow-ups</h2><form onSubmit={(event) => { event.preventDefault(); if (note.trim()) activity.mutate(); }}><label>Activity type<select value={type} onChange={(event) => setType(event.target.value as LeadActivityType)}>{["call", "whatsapp", "meeting", "email", "note"].map((value) => <option key={value}>{value}</option>)}</select></label><label>Follow-up note<textarea value={note} onChange={(event) => setNote(event.target.value)} /></label><button className="button button--primary" disabled={activity.isPending}>{activity.isPending ? "Saving…" : "Add follow-up"}</button></form>{activity.isError ? <p role="alert">Follow-up could not be saved.</p> : null}<ol className="lead-timeline">{activities.data.items.map((entry) => <li key={entry.id}><strong>{entry.type}</strong><span>{entry.note}</span><small>{new Date(entry.occurredAt).toLocaleString()}</small></li>)}</ol></section></div></section>;
}
