import { useMutation, useQuery } from "@tanstack/react-query";
import { useState } from "react";
import { StyleSheet, Text, View } from "react-native";

import type { AuthenticatedSession } from "../../contracts/session";
import { ApiError } from "../../core/http/apiClient";
import { privateQueryKey } from "../../core/query/queryClient";
import { useInvalidateEvent } from "../../core/query/useInvalidation";
import { useConfiguredRuntime } from "../../runtime/RuntimeProvider";
import { Button, Field } from "../../ui/primitives";
import { colors, fonts, radii, spacing } from "../../ui/tokens";
import { extractRecords, recordId, recordSubtitle, recordTitle } from "../workspace/recordPresentation";

export function EvaluationWorkspace({ subjectUserId, session }: { readonly subjectUserId: string; readonly session: AuthenticatedSession }) {
  const context = useConfiguredRuntime(); const invalidate = useInvalidateEvent(); const [open, setOpen] = useState(false); const [score, setScore] = useState("80"); const [comments, setComments] = useState(""); const [start, setStart] = useState(() => `${new Date().getUTCFullYear()}-01-01T00:00:00.000Z`); const [end, setEnd] = useState(() => `${new Date().getUTCFullYear()}-12-31T23:59:59.000Z`); const [error, setError] = useState<string | null>(null);
  const canRead = session.authorization.permissions.includes("organization.evaluation.read"); const canCreate = session.authorization.permissions.includes("organization.evaluation.create");
  const history = useQuery({ queryKey: privateQueryKey({ environmentId: context.environment.environment.id, userId: session.user.id }, "management", "evaluations", subjectUserId), queryFn: ({ signal }) => context.runtime.api.authenticated.get<unknown>(`/evaluations/${encodeURIComponent(subjectUserId)}?limit=100&offset=0`, { signal }), enabled: canRead });
  const save = useMutation({ mutationFn: () => { const numericScore = Number(score); if (!Number.isFinite(numericScore) || numericScore < 0 || numericScore > 100 || !comments.trim() || Number.isNaN(new Date(start).getTime()) || Number.isNaN(new Date(end).getTime()) || new Date(end) < new Date(start)) throw new Error("VALIDATION"); return context.runtime.api.authenticated.post("/evaluations", { subjectUserId, periodStartAt: new Date(start).toISOString(), periodEndAt: new Date(end).toISOString(), score: numericScore, comments: comments.trim() }); }, onSuccess: async () => { setOpen(false); setComments(""); await invalidate("management-changed"); }, onError: (cause) => setError(cause instanceof Error && cause.message === "VALIDATION" ? "Enter a 0–100 score, valid date range, and assessment comments." : cause instanceof ApiError ? cause.message : "The evaluation could not be saved.") });
  const evaluations = extractRecords(history.data);
  if (!canRead && !canCreate) return null;
  return <View style={styles.section}><View style={styles.heading}><Text accessibilityRole="header" style={styles.title}>Evaluations</Text><Text style={styles.copy}>Manager and Head assessments remain separate from backend-calculated KPI.</Text></View>{canCreate && !open ? <Button label="Create evaluation" variant="secondary" onPress={() => setOpen(true)} /> : null}{open ? <View style={styles.form}><Field label="Period start (ISO 8601)" value={start} onChangeText={setStart} /><Field label="Period end (ISO 8601)" value={end} onChangeText={setEnd} /><Field label="Score (0–100)" value={score} onChangeText={setScore} keyboardType="decimal-pad" /><Field label="Assessment comments" value={comments} onChangeText={setComments} multiline />{error ? <Text accessibilityLiveRegion="assertive" style={styles.error}>{error}</Text> : null}<View style={styles.actions}><View style={styles.action}><Button label="Cancel" variant="quiet" disabled={save.isPending} onPress={() => { setOpen(false); setError(null); }} /></View><View style={styles.action}><Button label="Save evaluation" loading={save.isPending} onPress={() => save.mutate()} /></View></View></View> : null}{canRead && history.isPending ? <Text style={styles.copy}>Loading evaluation history…</Text> : null}{evaluations.map((record, index) => <View key={recordId(record) ?? `evaluation-${index}`} style={styles.entry}><Text style={styles.entryTitle}>{recordTitle(record, index)}</Text>{recordSubtitle(record) ? <Text style={styles.copy}>{recordSubtitle(record)}</Text> : null}{typeof record.score === "number" ? <Text style={styles.score}>{record.score}/100</Text> : null}</View>)}</View>;
}

const styles = StyleSheet.create({ section: { gap: spacing.md }, heading: { gap: spacing.xs }, title: { color: colors.ink, fontFamily: fonts.semibold, fontSize: 20 }, copy: { color: colors.inkMuted, fontFamily: fonts.regular, fontSize: 12, lineHeight: 18 }, form: { gap: spacing.sm, padding: spacing.md, borderRadius: radii.surface, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.surface }, error: { color: colors.danger, fontFamily: fonts.regular, fontSize: 12 }, actions: { flexDirection: "row", gap: spacing.sm }, action: { flex: 1 }, entry: { padding: spacing.md, gap: 4, borderRadius: radii.control, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.surface }, entryTitle: { color: colors.ink, fontFamily: fonts.semibold, fontSize: 14 }, score: { color: colors.violet, fontFamily: fonts.bold, fontSize: 16 } });
